### ISSUE TITLE
Display history contents (like 'history' in many UNIX shells)

### ISSUE THREAD

**Issue by ghost** [mridgers/clink#118]
_From [calom...@gmail.com](https://code.google.com/u/107684926412812083209/) on April 29, 2013 22:57:22_

I couldn't find a way to list the current history contents.

Something like:

[host:~] history
     1  13:17   ls bin
     2  13:17   ls tmp
...

I think this is useful since I find myself often doing this:

[host:~] history | grep <some old command>

Instead of C-R / C-S.

I took a look at the code but couldn't quite figure out where to add this functionality. It shouldn't be too hard though (famous last words). I'd be willing to give this a try and send you a patch if this really requires a code change! What version of the product are you using? On what operating system? v0.3.1 on Windows 7

_Original issue: http://code.google.com/p/clink/issues/detail?id=119_

**Comment by vitalybe** [comment]
I am confused - If Clink can search the history using C-R, then it has the data stored somewhere? And if it is stored, why can't it print it to console?

**Comment by mridgers** [comment]
There is a workaround; enable Clink's history_io option and create history.bat somewhere in your path that prints the history file.

You are correct that the history is somewhere in the cmd.exe process and available to be printed. Firstly it is import _who_ does the printing. Cmd.exe isn't aware of the history so it is unable to print it. But if Clink does the printing then it would not be possible to pipe or redirect the output and I can imagine that "history|findstr build" is not uncommon.

So for something like "history|findstr ..." to work Clink needs to modify the command line returned to cmd.exe to replace "history" with something suitable. This is the second piece to the puzzle - it isn't trivial to manipulate cmd.exe commands lines. These are all valid for example;

```
C:\>echo foobar 1>history
C:\>npapi history --show
C:\>for /f %d in ('history') do @echo %d
C:\>@(@(@(@(history))))|findstr foobar
```

A naive string replace doesn't cut it - only the last two above actually intend to run the 'history' command. There's a few other ways this could be solved, such as the history.bat, or an alias, or even some IPC mechanisms - each with their own pros and cons.

**Comment by vitalybe** [comment]
That worked great. Thank you for the detailed explanation.

In case it makes it faster for someone else, here is what you need to run to configure:

`clink set history_io 3`

Then make a batch in a PATH dir like that (if use Cmder, can do exactly like that):

`@cat %CMDER_ROOT%\Config\.history`
