### ISSUE TITLE
Option to disable header?

### ISSUE THREAD

**Issue by ghost** [mridgers/clink#153]
_From [herzscha...@gmail.com](https://code.google.com/u/101443510349882706700/) on November 02, 2013 14:08:31_

I want to have a clean command line, so I've downloaded ConEmu and configured it. It's looking pretty good, but the Clink header on each run annoys me.

Is there any way I can remove these? I mean, running a `cmd /k cls` doesn't help. I don't know what would...

_Original issue: http://code.google.com/p/clink/issues/detail?id=154_

**Comment by 5p0ng3b0b** [comment]
In windows registry:
HKEY_CURRENT_USER\Software\Microsoft\Command Processor\AutoRun
Add the -q option
"C:\Program Files (x86)\clink\clink.bat" inject -q --autorun --profile ~\clink
Works with ConEmu.

**Comment by garoto** [comment]
+10 points for bumping an imported issue from google code on an abandoned repo. Kudos to you sir. GH should have a bling for cases like these.

**Comment by 5p0ng3b0b** [comment]
Necroposting never dies!

**Comment by chrisant996** [comment]
> Necroposting never dies!

@5p0ng3b0b do you know about the current replacement repo, and all the improvements from the past several years? 

https://github.com/chrisant996/clink

**Comment by 5p0ng3b0b** [comment]
Yup thx it is what I am using. I borked my .BAT file assosiation and fixing it led to reinstall of clink and was refiguring out hiding the banner again. I knew it worked on hijacking cmd.exe and remembered it was a reg setting I found using autoruns.

**Comment by chrisant996** [comment]
> Yup thx it is what I am using. I borked my .BAT file assosiation and fixing it led to reinstall of clink and was refiguring out hiding the banner again. I knew it worked on hijacking cmd.exe and remembered it was a reg setting I found using autoruns.

Ok, then you've posted in the wrong repo.  🙃  The repo you posted in is the mridgers repo which has been abandoned for 7+ years.

In the [chrisant996/clink](https://github.com/chrisant996/clink) repo, the recommended way to hide the banner is to use the [clink.logo](https://chrisant996.github.io/clink/clink.html#clink_logo) setting, rather the fiddling with the registry.  Also, the [Common Configuration](https://chrisant996.github.io/clink/clink.html#common-configuration) section in the documentation covers that setting as well as others (and has a section specifically on upgrading from the old v0.4.9 version as well).

Consider using the new repo for future issues and discussions.
