### ISSUE TITLE
Enable history-search with arrow keys

### ISSUE THREAD

**Issue by ghost** [mridgers/clink#164]
_From [b.r.carl...@gmail.com](https://code.google.com/u/115175814144991020003/) on December 04, 2013 09:53:22_

On Linux I have this in my .inputrc:
# Incremental searching with Up and Down

"\e[A": history-search-backward
"\e[B": history-search-forward

I have put the same in clink_inputrc (in ...APPData\Local\clink)
but I guess I should use some other code to capture arrow up and down.

It would be nice to have a way to find out which code to use. And until we get such a feature, does anyone know. Or could I build clink and set a breakpoint or add a printout somewhere?

_Original issue: http://code.google.com/p/clink/issues/detail?id=165_

**Comment by xak2000** [comment]
To make it clear, this is what you need to put into `%userprofile%\clink_inputrc`:

```
"\e`H": history-search-backward            # arrow up
"\e`P": history-search-forward             # arrow down
```

Works with Clink v0.4.9 [git:2fd2c2]

**Comment by John-Ao** [comment]
As tested with Clink v1.3.9.2e99f4, to use up and down arrow keys for history search, `%userprofile%\clink_inputrc` should be 

```
"\e[A": history-search-backward            # arrow up
"\e[B": history-search-forward             # arrow down
```

**Comment by raveren** [comment]
I did these steps to actually emulate Fish shell behaviour and did not have to create any machine-specific files (a.k.a. kept cmder portable):

https://github.com/cmderdev/cmder/issues/2184#issuecomment-1311456578

**Comment by chrisant996** [comment]
This is the old mridgers repo, which has been abandoned for about 6 years. You're looking for the https://github.com/chrisant996/Clink repo instead.

Also, the steps listed in the linked Cmder issue won't work right.  See my reply there.

**Comment by david-alvarez-rosa** [comment]
Also with Emacs bindings in `~/AppData/Local/cmder/config/.inputr`

```
"\e[A": history-search-backward  # arrow up
"\e[B": history-search-forward   # arrow down
"\C-n": history-search-forward   # Ctrl+N
"\C-p": history-search-backward  # Ctrl+P
```

**Comment by chrisant996** [comment]
> Also with Emacs bindings in `~/AppData/Local/cmder/config/.inputr`
> 
> ```
> "\e[A": history-search-backward  # arrow up
> "\e[B": history-search-forward   # arrow down
> "\C-n": history-search-forward   # Ctrl+N
> "\C-p": history-search-backward  # Ctrl+P
> ```

@david-alvarez-rosa You replied in an abandoned repo.
The active repo is https://github.com/chrisant996/clink.
