### ISSUE TITLE
is unix history command available?

### ISSUE THREAD

**Issue by ghost** [mridgers/clink#172]
_From [edsanj...@gmail.com](https://code.google.com/u/106770952329660426442/) on December 20, 2013 21:20:01_

Hi all,

is it possible to have the list of the past command typed, same as unix history command.

If not, can be implemented as custom lua script?

Thanks
Ed

_Original issue: http://code.google.com/p/clink/issues/detail?id=173_

**Comment by albfan** [comment]
You will not have actual session avaliable until you exit, but here is my to cents:

doskey history=cat C:\Users\X53526FA\AppData\Local/clink/.history $*
doskey lhg=cat C:\Users\X53526FA\AppData\Local/clink/.history $B grep $*

`lhg` stands for ls history grep, and it's a handy alias

**Comment by mridgers** [comment]
If you enable the history_io setting (available from v0.4.3) then the .history file will be written to every line entered. Native support for the history command is under way, albeit slowly.

**Comment by albfan** [comment]
That's a long time wanted feature. It's my default config on *nix systems. 

Can you share some clues about your plans? Over all I miss `!!$` and `!!:x`. I use it all the time with

    > mkdir blablabla
    > cd !!$

or 
    
    > super-complex-command
    > echo !!:x > %userprofile%/bin/handy-script.cmd

**Comment by mridgers** [comment]
Readline's history expansion works fine in Clink [as per the manual at least](http://cnswww.cns.cwru.edu/php/chet/readline/history.html).

As for plans, I'm working on detailed parsing of the entered line so Clink can condition it, expose it to Lua before it's returned to cmd.exe, etc. Part of that will be support for "history", and perhaps Bash-style backtick expansion.

**Comment by joce** [comment]
Hello Martin. Last comment on this issue is almost a year old. Do you have an ETA for the implementation of the bash-like history command? Is it still on your radar?

**Comment by mridgers** [comment]
I've given it some though, but not a lot to be honest. Clink's not got many new features simply because most of my time gets spent addressing issues. I do have a working parser for entered lines but haven't been able to get it to the point where it can be used to offer solid post-processing of a line before it's handed back to cmd.exe.

Bash's built-in 'history' command does quite a lot. Is there a common use-case that's particulary important? I wonder if this is it;

```
C:\>history | grep dir
  5  dir c:\foobar
 21  dir c:\windows
C:\>!21
```

**Comment by bostone** [comment]
Personally I think this is huge oversight. I just installed Clink with sole purpose to have a history and turns out I can't have it? Real disappointment for me

**Comment by regisbsb** [comment]
Create a bat file called history in windows folder.
Put the command in this answer:
https://superuser.com/questions/1019441/getting-the-list-of-command-history-using-clink

`type "%LOCALAPPDATA%\clink\.history"`

But by default clink writes history only on exit, to change it: `clink set history_io 1` or modify history_io value in %LOCALAPPDATA%\clink\settings
Done.

**Comment by albfan** [comment]
@mridgers So you finally made it. Awesome

**Comment by aleksander351** [comment]
You can also put the bat file into the C:\Users\<USER> folder.
