### ISSUE TITLE
support silent/quiet from settings file

### ISSUE THREAD

**Issue by ghost** [mridgers/clink#178]
_From [daveydav...@gmail.com](https://code.google.com/u/105725977711317285348/) on January 13, 2014 03:20:23_

What steps will reproduce the problem? 1.install clink, auto-inject
2.build boost bootstrap;b2
3.see clink display copyright info for each compile-c-c++. What is the expected output? What do you see instead? See in code that you can set the cmdline args -quiet or -silent.  Not sure where to change the auto-inject'd clink args,  tried setting silent=1 or quiet=1 in settings, does not work. What version of the product are you using? On what operating system? output from my build on a windows 7 x64, but building x86.

msvc.archive bin.v2\libs\wave\build\msvc-11.0\debug\address-m
clink v0.3.1 [git:5c9a90](c) 2013 Martin Ridgers http://code.google.com/p/clink Copyright (c) 1994-2012 Lua.org, PUC-Rio
Copyright (c) 1987-2010 Free Software Foundation, Inc.

common.copy stage64\lib\libboost_wave-vc110-mt-gd-1_53.lib
bin.v2\libs\wave\build\msvc-11.0\debug\address-model-64\archi
        1 file(s) copied.
clink v0.3.1 [git:5c9a90](c) 2013 Martin Ridgers http://code.google.com/p/clink Copyright (c) 1994-2012 Lua.org, PUC-Rio
Copyright (c) 1987-2010 Free Software Foundation, Inc.

...updated 1262 targets... http://www.boost.org/boost-build2/doc/html/index.html Please provide any additional information below. I'd quickly modify the registry setting if I knew where to go, to add the setting in the cmdline args...  but instead i looked at the code.

Looks like we'd need to update settings.c, to include the silent/quiet option, i think we need to also add it to self.lua(not sure about this),
and then the dll.c in success():76. 

```
if (!g_inject_args.quiet)
{
    puts(g_clink_header);
    puts("  ** Press Alt-H to show key bindings. **\n");
    puts(g_clink_footer);
}
```

checking for the setting.

I haven't yet tried to build clink myself...
I can create a patch if wanted.

Thank you for a great project!

--dave
linked to clink from this page on my website: http://dave.thehorners.com/tech-talk/windows-os/476-windows-shell-bat-cmdexe-batch-tips

_Original issue: http://code.google.com/p/clink/issues/detail?id=179_

**Comment by mrdaemon** [comment]
Coming late to the party, and on a closed issue too, but I'd just like to leave this here for prosperity -- I couldn't get `autorun -v` to eat the properly quoted string and the single quoted string didn't work very well, so should you stumble upon this via googling like I did, you can modify the AutoRun value directly in the registry.

For reference, the keys are:

* HKLM\Software\Microsoft\Command Processor\AutoRun    (for native)
* HKLM\Software\Wow6432Node\Microsoft\Command Processor\AutoRun  (for wow64)

There I was able to directly input `"C:\Program Files (x86)\clink\0.4.4\clink" inject --quiet --profile "~\clink"`as my AutoRun string without issues.

It would be nice if there were more details about how `clink autorun -v` works, the help is kind of elusive and generic. A usage example would go a long way...
