### ISSUE TITLE
Use windows cmd tab completion?

### ISSUE THREAD

**Issue by CarlosOnline** [mridgers/clink#190]
Is it possible to modify clink TAB completion to work like windows TAB completion which cycles thru the different folder names when matching folder names?

For example:

1st TAB:
c:> Program<TAB> --> c:\Program Files

2nd TAB:
c:> Program<TAB> --> c:\Program Files (x86)

**Comment by mateusz-matela** [comment]
This kind of works for me, but one thing missing is that SHIFT+TAB should cycle in the opposite direction.
Is it possible to configure it?

**Comment by mridgers** [comment]
In the current version of Clink it isn't possible to bind Shift-Tab unfortunately, but as you can see above this has been been fixed and will be available soon (it is already available in the Dropbox builds).

**Comment by nazikus** [comment]
I have tried these configs:
"\t":   menu-complete
"\e`Z": menu-complete-backward

forward works ok, but not backward.

I have also tried \e[Z, \e\t, ^[[Z for backward and it didn't work neither.

clink 0.4.4, Win8 x64

**Comment by mridgers** [comment]
The Shift-Tab fix support isn't in 0.4.4, so that is why backwards didn't work for you. I really need to prepare an update! In the mean time you can try a version from [here](https://www.dropbox.com/sh/hqbrpkf0dpmmizq/AAADT-mwBCPTk-Tl83D5GGGja/20150713_f4c512?dl=0).

**Comment by nazikus** [comment]
great. thank you!

ps
why not to put dev builds as pre-release (in releases)?

**Comment by mridgers** [comment]
> why not to put dev build as pre-release (in releases)?

No real reason really. I was using Dropbox when Clink lived on Google Code and it's all conveniently automated. I've not looked into migrating it over use what Github provides.

**Comment by grantelledge** [comment]
This file has been renamed (I believe), and the contents are different -- much more readable, but unfortunately it makes this answer not work. I can't seem to find a solution online for this on 1.6.0, which surprised me. Any ideas?

**Comment by sskras** [comment]
Probably worth trying the new repo: https://github.com/mridgers/clink/issues/579
