### ISSUE TITLE
need a way to start original cmd.exe

### ISSUE THREAD

**Issue by techtonik** [mridgers/clink#230]
Some of my Python scripts that execute external programs through shell are broken and I wonder if `clink` is guilty. Is there a way to temporarily disable clink without uninstalling? Can find anything in docs.

**Comment by moshahmed** [comment]
To Run your script in a vanilla cmd without clink, start a another cmd
`  start cmd /C "yourscript", `
Don't know how to disable clink temporarily.

**Comment by timgoodman** [comment]
If you just want to launch a single non-clink cmd window:

You can temporarily set the CLINK_NOAUTORUN environment variable, and then unset it after you launch the new cmd window.
`set "CLINK_NOAUTORUN=1" && start cmd && set "CLINK_NOAUTORUN="` 

Note: I've only tested this on the **chrisant996/clink** fork, so I'm not 100% sure it works in **mridgers/clink**

**Comment by chrisant996** [comment]
> `CLINK_NOAUTORUN`

@timgoodman No, that env var does not exist in the abandoned mridgers version.

**Comment by chrisant996** [comment]
@timgoodman this post was last commented on 8 years ago, and this repo is abandoned.

**Comment by timgoodman** [comment]
Thanks for clarifying that, @chrisant996 .

I found my way to this thread when doing a web search for how to skip autorun, before I spotted the helpful comment about "CLINK_NOAUTORUN" in `clink inject --help` 😊
