### ISSUE TITLE
clink.prompt broken in Windows 10 Technical Preview

### ISSUE THREAD

**Issue by MartiUK** [mridgers/clink#253]
Sorry if this counts as jumping the gun!

https://github.com/bliker/cmder/blob/master/config/prompt.lua
https://github.com/bliker/cmder/blob/master/config/git.lua

See bliker/cmder#279.

**Comment by Festum** [comment]
Thank you @mridgers it also fix mine in build 9888.

**Comment by luisrudge** [comment]
@mridgers dropbox link is 404 :(

**Comment by luisrudge** [comment]
Oh, version 0.4.3 fixed the problem. Thanks!

**Comment by LeG3nDz** [comment]
@luisrudge Can you display the link ? ::)

**Comment by luisrudge** [comment]
@LeG3nDz ops, sorry! It's on the releases tab
https://github.com/mridgers/clink/releases/tag/0.4.3

**Comment by cooper6581** [comment]
I was able to solve this issue on Win7 by removing my system installation of clink. Even when clink 0.4.4 was installed, the lambda prompt didn't start working until I removed my system installation.
