### ISSUE TITLE
Clink ignores the standard readline init file (~/.inputrc)

### ISSUE THREAD

**Issue by pahindman** [mridgers/clink#258]
Clink can only be configured by either editing `clink_inputrc_base` in the clink installation dir, or `clink_inputrc` in the clink profile dir.  It would be nice if clink could use the same readline configuration that other programs use.

**Comment by rivy** [comment]
Actually, IMO, it's not particularly ideal; using the default ".inputrc" file would be better and more compatible with other platforms.

As far as incompatibilities, the inputrc `$if` directive was specifically designed help with application variations. When using gnu readline, setting `rl_readline_name` sets the application name which can be used in the inputrc to customize behavior.

For example, set `rl_readline_name` to "CMD" (for example) and then the ".inputrc" file can be customized as needed by using:

```
... <common settings>
$if CMD
... <CMD settings>
$endif
... <more common settings>
```

Then a single inputrc file can be constructed which can be used for all shells.

**Comment by rivy** [comment]
:+1:
