### ISSUE TITLE
clink ignores keys

### ISSUE THREAD

**Issue by xverges** [mridgers/clink#284]
If I have a `clink_inputrc` with `ctrld_exits = 0`, the console ignore me whenever I press the `c` or the `s` keys. I comment out this line, and the keys work again. Some `history_*` entries caused other keys to be ignored. Puzzling.

**Comment by mridgers** [comment]
The clink_inputrc is where you configure the GNU Readline library (detailed [here](http://cnswww.cns.cwru.edu/php/chet/readline/readline.html)). Lines like "ctrld_exits = 0" in this file is like rebinding keys which will explain why certain keys stop working for you.

If you want to change Clink-specific settings then you should use the "clink set" command (or you can manually edit the "settings" file). Running "clink set --help" should show you all you need to know.

**Comment by xverges** [comment]
I was not careful enough reading the documentation. Thanks for your time and apologies for the noise.
