### ISSUE TITLE
Log command input and output to file

### ISSUE THREAD

**Issue by ettermyra** [mridgers/clink#285]
Hi,
First off! Great work!
I've got a request for a feature which involves logging command input and command output to file along with timestamps, username etc. What I understand from the documentation, I can read the readline buffer, but is there a way to read the results from the executed command? I'm currently working on a small project that need to have a complete trace along with time stamps etc. I know there are security concerns regarding this of course, however the traceability is way more important.

Perhaps I could implement it myself and contribute to the project. Perhaps you then could point me in the right direction in order to save time, where to implement such a routine. I'm not too familiar with your code base. I guess the Lua approach would be the best one?

Best regards
/Thomas

**Comment by mridgers** [comment]
Capturing command input/output is beyond the scope of Clink to be honest. Its remit is to improve the editing of command lines into cmd.exe and once a line's entered Clink is no longer involved and it's all cmd.exe's business. As neither Clink or its Lua scripts actually execute these commands, I'm sorry to say that what you're trying to achieve isn't really possible with Clink. I don't know the details of your requirements of course, I can imagine it would be easier to write a basic REPL in something like Python or Lua as you can then quite easily capture user input and command output.
