### ISSUE TITLE
Toggle window size and quick edit

### ISSUE THREAD

**Issue by borisbu** [mridgers/clink#290]
Hi Martin, I use clink, thanks for programming it. I have a problem with the quick edit mode. Whenever I cange the window size I lose the quick edit mode, and when I check the quick edit mode, I lose the window size. Is that a general problem of clink, or is something wrong with my setup?

**Comment by mridgers** [comment]
Clink doesn't modify any console settings so it's hard to reason how it would be involved here. Windows does some fairly odd things with console settings so I can imagine that that might be playing a part here. For example, if you change properties for the window, Windows will store those settings per-shortcut/executable name in the registry. Running a different shortcut but named the same it will then load these settings, even though they're not related. So pay attention to how you're launching cmd.exe and what it's console settings are (right click -> properties), and look what's stored in the registry (HKCU/Console I think).

Failing that, I'd be interested if you can identify some repro steps with/without Clink that demonstrate it's involved somehow!

**Comment by mridgers** [comment]
Closing as I'm fairly certain it's a local issue. Feel free to reopen if you can find a way to reproduce the issue and show Clink's at fault.
