### ISSUE TITLE
FAR like suggestions

### ISSUE THREAD

**Issue by kosz78** [mridgers/clink#293]
Is it possible implement FAR like suggestions?:
![far_suggestion](https://cloud.githubusercontent.com/assets/3992195/6227294/f892a240-b6c7-11e4-81ce-d51261c2556b.png)

**Comment by mridgers** [comment]
Clink is essentially a wrapper around Readline and it is Readline that implements tab-completion and match display and it doesn't support this style of completion. It is something I have thought about though as I think there's better alternatives to tab-completion (such as FAR's curses-style popup). To implement it though would be quite involved, as some users will still like to use Readline I'm sure.

**Comment by kosz78** [comment]
Thank You for clarification.
