### ISSUE TITLE
Possible to clear the history?

### ISSUE THREAD

**Issue by UweKeim** [mridgers/clink#297]
_(I hope this is the correct place to ask a question)_

Having accidentially entered passwords, I want to delete my history (which is persisted between sessions).

Is this possible somehow?

**Comment by mridgers** [comment]
You have two choices; either delete the .history file or set the history_file_lines setting to -1 (and restart a few times). History is stored to disk in Clink's profile directory in the ",history" file. To find out where this is type "clink set" and use the same path as where the settings file is located.

In the future you might want to enable the history_ignore_space setting. With this set, Clink won't add lines to the history that are prefixed with whitespace.

**Comment by UweKeim** [comment]
Thank you, I've removed the lines in question from the `.history` file.

**Comment by bkmagnetron** [comment]
Where can I find this `.history` file?
