### ISSUE TITLE
inoperable in Telnet Client

### ISSUE THREAD

**Issue by matthias-oe** [mridgers/clink#299]
We are using the KpyM Telnet Server for remote access, which spawns a native cmd.exe and redirects the io-streams. We use KpyM because it supports client window resizing, doskey aliases and last but not least vim!

Trying to inject clink via telnet simply does nothing. No copyright output, no error message. Calling clink --help produces normal output. clink inject --nohostcheck doesn't help.

In a local cmd.exe environment on the remote box itseft, clink works as expected.

Are the any possibilities to find the basic cause?

thanks in advance.
matthias

**Comment by mridgers** [comment]
Can you post you clink.log file (it's in %userprofile%\appdata\local\clink). What I think is happening is that KpyM's telnet server has hooked the ReadConsoleW and WriteConsoleW api's in cmd.exe so Clink is unable to apply it's hooks. If that's the case there's not really anything that can be done. Clink's already applying it's hooks at the lowest level it can because there is so much contention for hooking cmd.exe amongst third party utilities.

**Comment by matthias-oe** [comment]
Thank you very much! I didn'd notice the log file...

There was a 32/64-bit mismatch. The machine is 64-bit while KypM is 32-bit, which leads into the problem discussed in http://superuser.com/questions/281730/system32-and-syswow64-on-windows-7. So KypM uses the 32-bit cmd.exe in system32 which is redirected to syswow64 by windows internally.

Calling explicitly "clink_x86.exe inject" solves the problem.

So the "bug" is in clink.bat. You may have a 32-bit cmd.exe on a 64-bit system, so checking the architecture leads to the wrong decision...

I found another way to detemine the runtime of cmd.exe from Thomas Langer at https://groups.google.com/forum/#!topic/alt.msdos.batch.nt/r5RxiY4qx3E (nearly at the bottom), which works for me:

set BitSystem=32
set BitConsole=32
REM test if running on a 64bit system
If defined programfiles(x86) set BitSystem=64
REM test if running in 32bit console on 64bit system
If %BitSystem% EQU 64 If NOT "%ProgramFiles%"=="%ProgramFiles(x86)%" set
BitConsole=64
echo running on %BitSystem%bit system in %BitConsole%bit console... 

regards
matthias
