### ISSUE TITLE
using the history to show older command doesn't clear output in cmd.exe, so parts of older and longer commands still show in cmd.exe

### ISSUE THREAD

**Issue by MagicAndre1981** [mridgers/clink#301]
using the history to show older command doesn't clear output in cmd.exe, so parts of older and longer commands still show in cmd.exe:

![Image of clink history issue](https://dl.dropboxusercontent.com/u/5749744/Bilder/Github/clink_history_2.png)

The command ends at ```.man``` but still shows parts of an earlier command:
```
PerfView /nogui userCommand DumpRegisteredManifest Microsoft-Windows-DotNETRuntime
```

**Comment by mridgers** [comment]
I've seen this on and off but never been able to get a repro when I'm in a position to investigate it. I really thinks it's dependent on environment like buffer size and cursor position as well as long lines in the history.

How did you navigate the history to cause this redraw issue (i.e. what keypresses)? What is the console's buffer size (you can run "mode" to find out)?

**Comment by MagicAndre1981** [comment]
Here is the output:

```
Status von Gerät CON:
    Zeilen:          9999
    Spalten:         100
    Wiederholrate:   31
    Verzögerungszeit:1
    Codepage:        850
```

I used the arrow keys on my keyboard to browse for older commands.

**Comment by MagicAndre1981** [comment]
Where you able to repro this and do you have any idea how to fix this?

**Comment by mridgers** [comment]
Yes, thanks, I am now able to reproduce this. There's a bug in Clink's handling of termcap requests from Readline, but I'm not sure of the fix yet as I'm getting unexpected values from Readline.

**Comment by MagicAndre1981** [comment]
thanks. Can we please get a new dev version, so that I can test the fix?

**Comment by mridgers** [comment]
Done. It's here; https://www.dropbox.com/sh/hqbrpkf0dpmmizq/AAAWH3BTi-ux90aWLKg0LaOka/20150407_ad2283

**Comment by MagicAndre1981** [comment]
thanks. I've installed that version now and I'll test it.

**Comment by MagicAndre1981** [comment]
It looks like the dev version fixed the issue.
