### ISSUE TITLE
download links broken on http://mridgers.github.io/clink/

### ISSUE THREAD

**Issue by maphew** [mridgers/clink#302]
...subject line says it all.

**Comment by mridgers** [comment]
They are the same links as can be found [on the repository's release page](https://github.com/mridgers/clink/releases/tag/0.4.4). Are these links also broken for you? For me they are fine.

**Comment by maphew** [comment]
strange, works for me now, but when reported I had to go to the release page to get the files. Maybe a CDN caching issue? {shrug}
