### ISSUE TITLE
Problem with premake

### ISSUE THREAD

**Issue by ksrik** [mridgers/clink#310]
When I tried to generate the make file, I got some errors.
My Command is:

	D:\GitRepo\clink\clink>lua premake4.lua gmake

But I got this error message:

	lua: premake4.lua:56: attempt to index global 'premake' (a nil value)
	stack traceback:
	        premake4.lua:56: in main chunk
	        [C]: ?

I have installed `premake4`. 

What is wrong here?

regards,
srik

**Comment by mridgers** [comment]
Premake 5.0 is required now to make sure the .vcxproj files generated for vs2013 will build with v7.1a of the WinSDK (so resulting binaries support XP). I've updated the info in README.md to reflect this. Premake v5.0 is [here](http://premake.github.io).
