### ISSUE TITLE
Completion not showing files which might be 'executable' because of associations

### ISSUE THREAD

**Issue by jbrown123** [mridgers/clink#311]
I have a power point file in my current directory.  If I type the name of the file it will launch that file in PP.  Likewise for other file types (extension) such as doc, docx, txt, pl, html, etc.  These all launch in their respective applications.

Without clink loaded, the standard command interpreter will cycle through these files as you hit tab. Clink never shows them if you start the name at the beginning of the command line.

For example, suppose I have presentation.ppt in my current directory.  i should be able to type pre<tab> and have this autocomplete the filename.  When I hit enter it will launch in PP.  It works exactly this way without clink loaded.  However, after loading clink, hitting tab repeatedly in this condition does absolutely nothing.

**Comment by mridgers** [comment]
This is intentional. The theory being that the first word on a command line is likely to be an executable in the path so Clink only offers those for completion. The behaviour can be controlled with the "exec_match_style" and "space_prefix_matches_files" settings. Run "clink set" to see current values, set them, and for detailed info on each setting.

**Comment by jbrown123** [comment]
Martin,

Thanks for the response. Unfortunately I've tried every combination of
settings for "exec_match_style" and "space_prefix_matches_files" (-1 to
2; 0 or 1) and none of them allow you to auto complete a non-executable
file in the local directory as the first item on the command line.

The closest I can come is to put a space as the first character and then
TAB will auto complete the name as expected.

Maybe I'm missing something. Could you please elaborate on what
configuration of options allows CWD filename completion at the start of
the command line?

My example would be having a TXT file in the local directory (say
abc.txt). If I type the filename, i.e. abc.txt, and hit enter the
Windows file associations cause the file to be opened in notepad.
Standard windows command prompt, with auto complete enabled, will cycle
through the files in the current directory that match the pattern (say
you type ab<tab>) and allow you to launch the text file into notepad.

I can't reproduce this behavior with any combination of clink
configurations I have found.

Thanks,

- James


On Mon, Apr 20, 2015, at 01:52 AM, Martin Ridgers wrote:
> This is intentional. The theory being that the first word on a command
> line is likely to be an executable in the path so Clink only offers
> those for completion. The behaviour can be controlled with the
> "exec_match_style" and "space_prefix_matches_files" settings. Run
> "clink set" to see current values, set them, and for detailed info on
> each setting.


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/mridgers/clink/issues/311#issuecomment-94385076

**Comment by mridgers** [comment]
1. Start Clink with default settings ("settings" file deleted, or run a fresh .zip download)
2. On an empty line, hit Tab twice to list possible completions. It will display a "Display all X possibilities?" prompt. These are executables in the path.
3. Run "set clink.exec_match_style=-1" to disable executable matching _just for this session_.
4. Press Tab twice again to list completions. Clink will show normal file completions for the current directory.
5. Run "clink set exec_match_style -1" to make the setting permanent.

Here's the above in one image;

![turn off exec matchings](http://i.imgur.com/bf2HGqb.png)

**Comment by mridgers** [comment]
Duplicate of #313

**Comment by jbrown123** [comment]
Does work with the default mapping of TAB.  If you change to clink-menu-completion-shim instead, this does not work.

**Comment by mridgers** [comment]
Unfortunately using Readline's menu completion is also working as I would expect. This is a bit puzzling. Here it is in action;

![menu completion](http://i.imgur.com/Wh47mIy.gif)

**Comment by jbrown123** [comment]
Figured it out ... there is a subtle difference between *set
clink.exec_match_style* and *clink set exec_match_style*. I rashly
assumed that the second one also set this for the current session which
apparently it does not.

Thanks,

- James


On Wed, Apr 22, 2015, at 03:13 PM, Martin Ridgers wrote:
> Unfortunately using Readline's menu completion is also working as I
> would expect. This is a bit puzzling. Here it is in action;


> menu completion


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/mridgers/clink/issues/311#issuecomment-95337587

**Comment by JThundley** [comment]
Sorry to re-open this, but what about tab-completing files that are **not** in the current dir, but are instead in your path? For example, I have a bunch of python scripts in my scripts dir which is in my path. Using clink set exec_match_style -1, I can autocomplete somescript.py when I'm in my scripts dir, but I'd like to tab autocomplete those scripts no matter where I am.

**Comment by TimHiggison** [comment]
@JThundley you probably don't care about this any more but for anyone googling the issue I had a similar one. I have clink running under cmder (ConEmu) and it wouldn't auto-complete shell script file names that are in my path.

It turns out that clink determines which files are considered executable by the environment variable PATHEXT. By default this contains ".EXE;.BAT;" etc. Add ";.PY" there and it should start working because files with extension .py will now be considered executable.

**Comment by JThundley** [comment]
Hey buddy, thanks! :)
