### ISSUE TITLE
Batch files stop working

### ISSUE THREAD

**Issue by UweKeim** [mridgers/clink#312]
Currently I'm having a strange issue on one Windows 2008 (non-R2) server:

Some batch scripts stop working randomly. When executing the batch files, they simply immediately return. No error, noch echo, even if the echo is in the very first line in the batch file. closing CMD and re-opening it sometimes help.

So I uninstalled clink, rebooted my machine, still same behaviour. I also created a new admin user. No change.

While I'm unsure whether to really blame clink for that, I would love to get an answer to **my following question**:

Is it possible that even after uninstalling clink there are some "artefacts" remaining on the system like some dangling hooks or some oddly registry keys or something like that?

Would be awesome if you could help me locating the issue so that I am sure clink is not to blame for this and I can look further.

**Comment by mridgers** [comment]
If Clink's DLLs are no longer on disk there's no way Clink involved so you can confirm that by looking where you had Clink installed. I make sure that the uninstaller doesn't leave any registry entries too. You can look [here](https://github.com/mridgers/clink/blob/master/installer/clink.nsi) to see what registry entries are used. Another way to get peace of mind that there's no Clink artefacts remaining is to inspect cmd.exe's loaded modules with [SysInternal's Process Explorer](https://technet.microsoft.com/en-us/sysinternals/bb896653.aspx) and confirm there's no Clink DLL loaded into the process. I can't really help you any further with the matter unfortunately.

**Comment by UweKeim** [comment]
Thanks a lot, Martin!

**Comment by UweKeim** [comment]
Quick update: it appears that [CS-Script is the cause of the issue](https://groups.google.com/forum/#!topic/cs-script/nmq3N6C1EYo), not Clink.
