### ISSUE TITLE
Opening  a command prompt takes now 5 seconds

### ISSUE THREAD

**Issue by xverges** [mridgers/clink#314]
I have been a happy user for a long time. Suddenly (sorry for the lack of detail), launching command prompts has become extremely slow. `start cmd.exe /k time` takes about 5 seconds. I deleted my `.history` file, and nothing changed.

**Comment by xverges** [comment]
Uninstalled and installed. No changes. I installed again (on top, without uninstalling), and asking not to autorun. Anyhow, autorun is enabled and it works as it used to. Not a clue of what has happened. Apologies for the noise.

**Comment by mridgers** [comment]
It would have been interesting to see what the autorun value was, in case that had somehow got in a bad state. Should this happen again, if you can capture a crash dump of the cmd.exe process that is stalled and get it to me, it will give an insight as to why it has stalled. Crash dumps can be created from Task Manager like this (similar on Win8);

![cmd.exe crash dump](http://i.imgur.com/rhDvUJ5.png)
