### ISSUE TITLE
Way to 'uninject' clink?

### ISSUE THREAD

**Issue by orlp** [mridgers/clink#316]
Is there a way to 'uninject' clink from a command process? I have clink automatically ran in every cmd session, and sometimes I want to debug something without clink interfering.

**Comment by mridgers** [comment]
Unfortunately not - the process of hooking into cmd.exe is a bit too invasive to reverse. The best solution you have is to either install/uninstall the autorun using "clink autorun" command or remove the autorun completely and have two "with and without Clink" cmd.exe shortcuts.
