### ISSUE TITLE
History is expanded inside quotes.

### ISSUE THREAD

**Issue by orlp** [mridgers/clink#317]
If you'd try to run the following command:

    git config --global alias.ls-files-root '!git ls-files'

With clink this would expand history inside the quotes, which you don't want. I know for one that with `zsh` single quotes prevents expansion of history.

**Comment by mridgers** [comment]
That's a bit awkward. It's GNU History library (part of Readline) that does the expansion. I wonder if vanilla Bash behaves the same way? Do single quotes mean anything specific to zsh, or to the example line you gave? Cmd.exe at least doesn't consider single quotes as a quoting mechanism for arguments with spaces.

**Comment by orlp** [comment]
GNU bash has the history expansion, and backslash and single quotes escape it:

http://www.gnu.org/software/bash/manual/html_node/History-Interaction.html
