### ISSUE TITLE
loosing history from other cmd windows after closing cmd window without typing there

### ISSUE THREAD

**Issue by alivanou** [mridgers/clink#318]
To reproduce set history_io to 3 and do the following:
1) open 2 cmd windows
2) execute "echo 10" in the first window and close it
3) close the second window
4) open a new cmd window - "echo 10" is missing from the history
Actually I found out this issue using ConEmu. If I have a few windows opened, but am not using the first one, all the history gets lost after closing ConEmu with "X" button.
Could you please fix that behavior?

**Comment by mridgers** [comment]
Thank you for the clear steps to reproduce the issue, and well spotted!
