### ISSUE TITLE
Random crash when starting a command prompt

### ISSUE THREAD

**Issue by superzadeh** [mridgers/clink#319]
Hi,

I have clink installed on server that frequently runs scheduled tasks and one of them failed recently, apparently due to clink_dll_x64.dll. Below is the error I saw in the Windows Event Log:
```
Faulting application name: cmd.exe, version: 6.1.7601.17514, time stamp: 0x4ce798e5
Faulting module name: clink_dll_x64.dll_unloaded, version: 0.0.0.0, time stamp: 0x53389bcc
Exception code: 0xc0000005
Fault offset: 0x000007fef6ad4740
Faulting process id: 0xa20
Faulting application start time: 0x01d09d9a98dff845
Faulting application path: C:\Windows\system32\cmd.exe
Faulting module path: clink_dll_x64.dll
Report Id: dc613227-098d-11e5-bf7e-00155d012a3d
```
It also appears that some dumps have been created by Windows, some Information logs right after the error mention it:

```
Fault bucket , type 0
Event Name: BEX64
Response: Not available
Cab Id: 0

Problem signature:
P1: cmd.exe
P2: 6.1.7601.17514
P3: 4ce798e5
P4: clink_dll_x64.dll_unloaded
P5: 0.0.0.0
P6: 53389bcc
P7: 000007fef6ad4740
P8: c0000005
P9: 0000000000000008
P10: 


Attached files:
C:\Users\<username>\AppData\Local\Temp\WERF94F.tmp.appcompat.txt
C:\Users\<username>\AppData\Local\Temp\WERF99E.tmp.WERInternalMetadata.xml
C:\Users\<username>\AppData\Local\Temp\WERF99F.tmp.hdmp
C:\Users\<username>\AppData\Local\Temp\WERF9FE.tmp.mdmp

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_cmd.exe_7d1ab52217abbaa9d023588ecce774f4335786_cab_bf42fa1a

Analysis symbol: 
Rechecking for solution: 0
Report Id: dc613227-098d-11e5-bf7e-00155d012a3d
Report Status: 0
```

Looking at the reporting queue (C:\ProgramData\Microsoft\Windows\WER\ReportQueue), it seems that this crash has happened 5 times in the last two months.

**Comment by superzadeh** [comment]
Here is what I found during in the "WERInternalMetadata.xml" file:

```
	<ProblemSignatures>
		<EventType>BEX64</EventType>
		<Parameter0>cmd.exe</Parameter0>
		<Parameter1>6.1.7601.17514</Parameter1>
		<Parameter2>4ce798e5</Parameter2>
		<Parameter3>clink_dll_x64.dll_unloaded</Parameter3>
		<Parameter4>0.0.0.0</Parameter4>
		<Parameter5>53389bcc</Parameter5>
		<Parameter6>000007fef6ad4740</Parameter6>
		<Parameter7>c0000005</Parameter7>
		<Parameter8>0000000000000008</Parameter8>
	</ProblemSignatures>
	<DynamicSignatures>
		<Parameter1>6.1.7601.2.1.0.272.7</Parameter1>
		<Parameter2>1033</Parameter2>
		<Parameter22>866d</Parameter22>
		<Parameter23>866d0a7bdb9f4d9f5a1f5420ad626147</Parameter23>
		<Parameter24>bd40</Parameter24>
		<Parameter25>bd4072d974c83a44f5cae7ea2237c8dc</Parameter25>
	</DynamicSignatures>
```

**Comment by mridgers** [comment]
This is very strange. Do you happen to have any of the mini dumps available? It looks like you've built Clink yourself or are using a build from Dropbox - if so, does include the fix for issue #304?

**Comment by superzadeh** [comment]
Yes, you have the two minidumps available here: http://1drv.ms/1QnDJIZ, however I haven't built clink myself, nor use a dropbox build.

**Comment by mridgers** [comment]
What version are you using? The "0.0.0.0" version number is what made me think you were using a Dev version, but now I see the "_unloaded" part so it's probably this way because the Clink DLL was being unloaded when it crashed.

**Comment by superzadeh** [comment]
I am using clink_0.4.1_setup.exe, that I downloaded from the official website. I added the installer I used to the OneDrive folder where the dumps are.

**Comment by mridgers** [comment]
This is a fairly confusing scenario. The mini dumps seem to show that it's crashed trying to call a callback that the staticly-linked CRT in Clink's DLL has registered. But Clink doesn't fully load it's DLL if cmd.exe is deemed not to be interactive (like a scheduled task for example) so that callback is invalid. I found this which describes exactly what I've seen in the mini dump;

https://support.microsoft.com/en-us/kb/2754614

0.4.1 was built with Visual Studio 2010 and that article says that the lingering callback was improved in 2012. So I think the best advise is to upgrade Clink to a newer version as they're built with 2013 now.

**Comment by superzadeh** [comment]
Thanks for the investigation. I will update Clink and let you know if this error still occurs
