### ISSUE TITLE
Completing (Tab) a python script doesn't work

### ISSUE THREAD

**Issue by giuspen** [mridgers/clink#323]
Let's say I have the script "my_script.py", if I type "my_" and then press Tab, this will not work/complete.
It works only for an executable like my_app.exe, this is annoying because I have to write "python my_script.py" if I want some completion on both "python" and "my_script.py".
Your work anyway is wonderful thank you.

**Comment by mridgers** [comment]
Clink uses the PATHEXT environment variable when it generates matches for executables. If you add the .py extension to this it will start completing Python scripts too (provided Windows knows how to launch .py scripts of course).

**Comment by giuspen** [comment]
That's great, maybe it would be worth mentioning this in the home page between the features:
- Context sensitive completion; 
--- Executables (and aliases) using the PATHEXT environment variable.
--- ....

**Comment by bdun** [comment]
Or even better could it use the results from ls -la to know if it is executable.  This already knows that some of my python files are executable (looks like this detects: #!/bin/python at the start of the file).

I also agree that a comment on the homepage about this would be useful as had the same issue.

Thanks for a great tool!
