### ISSUE TITLE
Disable startup message

### ISSUE THREAD

**Issue by mottosso** [mridgers/clink#324]
Sorry if this is a silly question, but I can't find my way around it.

Whenever I enter a subshell, I get a Clink welcome message.

```bash
> cmd
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.
Clink v0.4.4 [git:a60c0a] Copyright (c) 2014 Martin Ridgers
http://mridgers.github.io/clink
>
```

I typically circumvent the default windows message, by passing an empty string to `/K`, but clink doesn't seem to pick up on that.

```bash
> cmd /K
Clink v0.4.4 [git:a60c0a] Copyright (c) 2014 Martin Ridgers
http://mridgers.github.io/clink
>
```

Is there any way I can work around this?

Thanks

**Comment by mridgers** [comment]
Use the --quiet flag when "clink inject" is run. It looks like you're launching Clink via cmd.exe's autorun so you can run the following to update it;

```
clink autorun --install -- --quiet
```

**Comment by mottosso** [comment]
Thanks @mridgers!

**Comment by hickford** [comment]
>clink autorun --install -- --quiet
    autorun: invalid option -- `-i'

Try

    clink autorun --install -- --quiet

**Comment by mridgers** [comment]
I changed it after making that comment from "--install" to "install" because it didn't really make any logical sense for "install/uninstall/show" to be an options. They are mutually exclusive actions.

**Comment by pclausen** [comment]
Sorry for bumping an old thread, but I had the same issue and solved it by

`cmd /D `

where:
`/D     Disable execution of AutoRun commands from registry (see below) ?`

**Comment by thejustsoul** [comment]
This is not work in 0.4.9?
How to disable welcome/version message with every start cmd?

**Comment by kohanyirobert** [comment]
I wanted to do the same, but issuing `clink autorun install -- --quiet` although did update the registry entries for `cmd`'s AutoRun key this didn't work.

This did.

```
clink autorun set "\"<your-path>\clink\0.4.9\clink.bat\" inject --autorun --profile ~\clink"
```

**Comment by mvidaldp** [comment]
> 
> 
> Use the --quiet flag when "clink inject" is run. It looks like you're launching Clink via cmd.exe's autorun so you can run the following to update it;
> 
> ```
> clink autorun --install -- --quiet
> ```

Thanks for the tip. With the current version the command is next:
```bash
clink autorun install --quiet
```

**Comment by PiotrWieczorek98** [comment]
Updated command:
`clink autorun install -- --quiet`

**Comment by chrisant996** [comment]
> Updated command:
> `clink autorun install -- --quiet`

@PiotrWieczorek98 you've replied in the old repo that was abandoned many years ago. Visit the current repo at https://github.com/chrisant996/clink.  It has tons of enhancements and fixes.

It also has a setting that controls the startup message (none, short, full).

**Comment by The3ven** [comment]
C:\Program Files (x86)\clink\clink.bat" inject --autorun --quiet

**Comment by chrisant996** [comment]
@The3ven Yes.  But also, you've commented in the repo for the old abandoned version of Clink.  You might have been looking for the current version at https://github.com/chrisant996/clink, which is being actively developed and supported.
