### ISSUE TITLE
Disable history completion

### ISSUE THREAD

**Issue by gkruschina** [mridgers/clink#326]
Hi there,
is it possible to disable the history completion? 
I have trouble with passwords including the  "!"-char.

wbr
Günter

**Comment by mridgers** [comment]
There isn't currently a way to disable history completion but it would certainly be useful - I'll add such an option. Now that #317 has been fixed Clink won't expand characters inside single quotes (like Bash) which maybe of use to you.

**Comment by gkruschina** [comment]
Sorry, this does not work on my system.
I did the following steps:
1. clink.bat
2. dir
3. echo '!1'
Answer:
History expansion: echo 'dir'
'dir'

**Comment by mridgers** [comment]
I only pushed the code changes upstream 20 minutes ago!
