### ISSUE TITLE
Control valid flag start for commands

### ISSUE THREAD

**Issue by albfan** [mridgers/clink#327]
On git for windows "/" is not a start of flag, and it is used to locate branches on remotes "origin/master" "origin/develop"

It would be helpful to control which characters are allowed to be start of flag.

I guessed that this can be controlled on parser definition so I tried:

https://github.com/albfan/clink-completions/commit/ae213b329edd0581a78f0992e51616b5f7acbcce

but this leads to an error:

C:\Users\vagrant\AppData\Local.\clink\git.lua:218: attempt to index local 'parser' (a function value)

I'm totally newbie to lua. What is the correct syntax to override `is_flag()`, is that possible?

Another approach is to recompile clink. I do not use window toolchain so I try with mingw

https://github.com/albfan/clink

by now I have installed mingw 32 using this branch:

https://github.com/albfan/clink/commits/wip

If I manage to install mingw64 or tweak clink.bat to use 32bits instead of machine platform I confident this tweak should work. If I'm right and you find this interesting I guess clinks should be configurable at that point. Something like:

    parser:disable_window_flag_style()

would be helpful for a lot of command line tools.

**Comment by albfan** [comment]
These analysis is totally wrong. autocomplete for remote branches is solved here

https://github.com/albfan/clink-completions/commit/1f02095659b83a50f501e6ca219d96249d3a4323

**Comment by mridgers** [comment]
:+1:
