### ISSUE TITLE
permanent history does not work

### ISSUE THREAD

**Issue by ChristianZimpelmann** [mridgers/clink#328]
Hi,
the tool is very helpful. Thank you very much!

Unfortunately, the permanent history seems not to work for me. The .history file is also completely empty. history_file_lines is still the default 10000.

Do you have any suggestions what my problem could be? Let me know if you need any further information or if this is not the right place to ask this kind of question. I really tried to find an answer myself.

Best, Christian

**Comment by mridgers** [comment]
1. Does Clink have permission to write to the .history file?
2. I presume it isn't mark as read-only?
3. Are you using the history_io option?

**Comment by ChristianZimpelmann** [comment]
Thank you, Martin! It was indeed marked as read and execute access.

**Comment by mridgers** [comment]
Great! That was easy :)
