### ISSUE TITLE
autorun requires admin privs.

### ISSUE THREAD

**Issue by jtnord** [mridgers/clink#332]
Installing the AutoRun requires administrator privs as it [tries to write](https://github.com/mridgers/clink/blob/ac67756e666ea13b3b50fdfd4187c2149a029a4c/clink/loader/autorun.c#L65) to
`HKEY_LOCAL_MACHINE`.
However a per user autorun key is available in `HKEY_CURRENT_USER` and this should be used by default (with an option to install for everyone on the system if desired).

```
C:\Users\jnord>"c:\Program Files (x86)\clink\0.4.4\clink.bat" autorun -i
You must have administator rights to access cmd.exe's autorun

C:\Users\jnord>ver
Microsoft Windows [Version 6.3.9600]

C:\Users\jnord>cmd /?
....
If /D was NOT specified on the command line, then when CMD.EXE starts, it
looks for the following REG_SZ/REG_EXPAND_SZ registry variables, and if
either or both are present, they are executed first.

    HKEY_LOCAL_MACHINE\Software\Microsoft\Command Processor\AutoRun
        and/or
    HKEY_CURRENT_USER\Software\Microsoft\Command Processor\AutoRun
...
```

**Comment by mridgers** [comment]
Yes that's a good point. Wouldn't help in the installers case as "Program Files" needs administrator rights and that's the default. I'll make the autorun command default to HKCU.
