### ISSUE TITLE
debugging autocompletion

### ISSUE THREAD

**Issue by albfan** [mridgers/clink#334]
I'm trying https://github.com/pkulchenko/ZeroBraneStudio to debug autocompletion

Configuration seems easy: Add this to script

    local zbs="C:/projects/lua/ZeroBraneStudio"
    package.path = package.path .. ";./?.lua;".. zbs .. "/lualibs/?/?.lua;" .. zbs .. "/lualibs/?.lua" 
    package.cpath = package.cpath .. ";" .. zbs .. "/bin/?.dll;" .. zbs .. "/bin/clibs52/?.dll"
    require("mobdebug").start()

And launch it. - for clink issuing `Ctrl+Q` -

but this shows an error

    $ error loading module 'socket.core' from file 'C:\projects\lua\ZeroBraneStudio/bin/clibs52/socket\core.dll':
            %1 is not a valid Win32 application.

ZeroBraneStudio seems 32bits. Can I start clink in 32bits on a 64bit machine? I had tried to modify clink.bat:

    if /i "%PROCESSOR_ARCHITECTURE%"=="x86" (
        call :loader_x86 %*
    ) else if /i "%PROCESSOR_ARCHITECTURE%"=="amd64" (
        rem call :loader_x64 %*
        call :loader_x86 %*
    )

but that do not start clink injection.

Is there any working debug config for autocompletion?

**Comment by vladimir-kotikov** [comment]
I guess there is a module for debugging purposes, see https://github.com/mridgers/clink/blob/master/clink/lua/debugger.lua but i have never used it.

**Comment by albfan** [comment]
If it is based on RemDebug, it lacks from remote, which I think is esential for debug autocompletion (please correct me if I'm wrong) I don't see how to debug autocompletion other way.

https://github.com/pkulchenko/MobDebug/blob/master/src/mobdebug.lua seems a precursor project of zerobranestudio (it is from same developer) and it is based on remdebugger too (adding remote debug)

Maybe evolve clink debugger to mobdebug can be enough. 

@mridgers is there a way to debug autocompletion? remotely? can you tell us how you do it? or how to use debugger.lua from clink?

**Comment by vladimir-kotikov** [comment]
As i said i have never used a debugger for that :smile: The debugging for me is a good warm-up for my  brains :smile:

**Comment by albfan** [comment]
Using a fork of zerobranestudio

https://github.com/albfan/ZeroBraneStudio

and this on git.lua

    local zbs="C:/projects/lua/ZeroBraneStudio"
    package.path = package.path .. ";./?.lua;".. zbs .. "/lualibs/?/?.lua;" .. zbs .. "/lualibs/?.lua" 
    package.cpath = package.cpath .. ";" .. zbs .. "/bin/windows/x64/?.dll;" .. zbs .. "/bin/windows/x64/clibs/?.dll"
    require("mobdebug").start()

I have almost do it.

starting debug says it do not found lua51.dll (I suppose it needs a lua51.dll 64 bits). Luckily enough I have one from http://files.kaoriya.net/goto/vim74w64. I put it on system32 and debug starts, but instantly it fails with

    !!! CLINK'S CRASHED!
    !!! Something went wrong.
    !!! Writing mini dump file to: C:\Users\vagrant\AppData\Local.\clink/mini_dump.dmp

https://github.com/albfan/clink/raw/dump/dump/mini_dump.dmp

Without debugging it do not crash. Any ideas?

**Comment by mridgers** [comment]
Clink uses Lua 5.2. I can't imagine using a DLL build of Lua 5.1 is going to work. The mini_dump.dmp you have provided has the following callstack

```
hild-SP          RetAddr           Call Site
000000ec`2fbfde50 6f6e090a`2761756c lua51+0x3490
000000ec`2fbfde58 43272065`6c696620 0x6f6e090a`2761756c
000000ec`2fbfde60 676e696e`6e75523a 0x43272065`6c696620
000000ec`2fbfde68 6d657473`79735c00 0x676e696e`6e75523a
000000ec`2fbfde70 656b636f`735c3233 0x6d657473`79735c00
000000ec`2fbfde78 00007ffd`bc611386 0x656b636f`735c3233
000000ec`2fbfde80 206f6e09`0a276175 lua51+0x51386
000000ec`2fbfde88 00007ffd`bc5c39f9 0x206f6e09`0a276175
000000ec`2fbfde90 73776f64`6e69575c lua51+0x39f9
000000ec`2fbfde98 336d6574`7379735c 0x73776f64`6e69575c
000000ec`2fbfdea0 00000000`fffffffe 0x336d6574`7379735c
Unable to load image C:\projects\lua\ZeroBraneStudio\bin\windows\x64\clibs\socket\core.dll, Win32 error 0n2
*** WARNING: Unable to verify timestamp for core.dll
*** ERROR: Module load completed but symbols could not be loaded for core.dll
000000ec`2fbfdea8 00000000`6c589100 0xfffffffe
000000ec`2fbfdeb0 000000ec`2fc979a0 core+0x9100
000000ec`2fbfdeb8 00007ffd`bc611546 0xec`2fc979a0
000000ec`2fbfdec0 00000000`00000002 lua51+0x51546
000000ec`2fbfdec8 00000000`00000000 0x2
```

I don't have any of the correct symbols here so it's just return addresses but it's fairly clear that it isn't Clink that's segfaulted. Looks like someone has injected Lua51.dll into cmd.exe and that is the cause of the crash.

**Comment by mridgers** [comment]
When debugging Lua scripts with Clink I use the debugger.lua that @vladimir-kotikov linked to. I normally do something like this;

```lua
dofile("path/to/debugger.lua")

function my_function(value)
    pause()      -- This will cause debugger.lua to take control.
    value = value + 1
    print(value)
end
```

When the pause() function is called the debugger will take control which will then give output like the following;

```
Lua Debugger
Paused at file test.lua line 10 (0)
8       function my_function(value)
9           pause()
10***       value = value + 1
11          print(value)
12      end
Message: pause
Type 'help' for commands
[DEBUG]>
```

From there you can enter commands into the '[DEBUG]>' prompt to step execution, inspect values, etc.

**Comment by albfan** [comment]
A good example is all I needed. I would recommentd just add this plain to docs.
