### ISSUE TITLE
Line breaks 2 characters too early

### ISSUE THREAD

**Issue by markusgritsch** [mridgers/clink#337]
Clink v0.4.4 [git:a60c0a]

When entering text on the command line and reaching the right border of the console, the line breaks two characters too early:
![line_break](https://cloud.githubusercontent.com/assets/2684183/8851659/4122dd1e-3151-11e5-88ef-405ddec3ee9c.png)

This prevents ConEmu's "Detect line ends" feature from joining the lines when copying text.

Also discussed here:
https://code.google.com/p/conemu-maximus5/issues/detail?id=1948

**Comment by Stanzilla** [comment]
Uh, just noticed. My OCD!

**Comment by mridgers** [comment]
Never been too keen on that myself either to be honest. Fear not though, for I have a plan.

**Comment by Stanzilla** [comment]
Oh great, are there any new builds to test this? I can't see anything from this week on your Dropbox folder.

**Comment by mridgers** [comment]
That's my next plan - migrate from using Dropbox and use GitHub's release API for pre-releases. It is about time to cut 0.4.5 too I think.
