### ISSUE TITLE
clink doesn't work anymore with ConEmu

### ISSUE THREAD

**Issue by narnaud** [mridgers/clink#339]
Since [ConEmu](https://github.com/Maximus5/ConEmu) has moved to minhook for its hooking system, clink doesn't work anymore with it.

It seems to be coming from clink, see discussion here:
https://github.com/Maximus5/ConEmu/issues/270

**Comment by Maximus5** [comment]
BTW, you haven't shown used clink version. May be current version from master branch runs properly?

**Comment by narnaud** [comment]
I'm using clink 0.4.4, with ConEmu 180516.
I didn't try clink master though.

**Comment by mridgers** [comment]
There's really nothing that I can do here. It is ConEmu's decision to change from hooking cmd.exe's Import Address Table (IAT) to patching the prologue of functions that has introduced the issue and made itself incompatible with Clink. Clink was already using the prologue trampoline approach in order to avoid hook contention with third party tools like ConEmu as much as possible and this worked fine provided these tools used the IAT. To resolve the issue ConEmu need to not place its hooks where Clink was already applying its own.

**Comment by Maximus5** [comment]
> ConEmu need to not place its hooks where Clink was already applying its own.

In fact, clink hooks functions **after** ConEmu applies its own.

> BTW, long ago I've suggested to clink's author tighter integration with ConEmu, but the suggestion was declined. I mean, ConEmu hooks may provide interface for clink or, on the contrary, call clink exported functions.

**Comment by mridgers** [comment]
I was not referring to the order in which these hooks are applied - that is irrelevant. I am suggesting that as it was ConEmu's decision to make itself incompatible with Clink, it is ConEmu's responsibility to address the issue should it wish (just as Clink has done in the past when breaking functionality with ConEmu).

I did see your comment regarding a declined "tighter integration", however I am not entirely sure what you are referring to. I recall only a brief discussion regarding calling an accidental export from Clink's DLL directly - an approach which I explained would skip important functionality. Certainly not a discussion on tighter integration.

**Comment by Maximus5** [comment]
It's impossible to ConEmu to "do not place its hooks where Clink was already applying its own". Hooks are required for functionality.

As for responsibility, the only thing I can do - create a pull request for clink. As I've said, I hope that minhook will work properly.

Why not a discussion? You declined calling clink exports from ConEmu. Well, you are the author, it's your right. But that is a possibility to deal with any breaking changes in ConEmu. Or ConEmu may provide some exports for clink.
But as I understood, you want to make clink independent from ConEmu, don't you?

**Comment by Maximus5** [comment]
As I supposed, minhook JMP implementation is working.

**Comment by paulbombarde** [comment]
I just tested Maximus5's fork and I confirm it is working, either from conemu, console2 or raw cmd. It would be really nice if you could get to a working solution. Both works are trully amazing. They are both part of my daily workflow.

**Comment by uahim** [comment]
+1

**Comment by jibsen** [comment]
I had the same problem, so I had gone back to using ConEmu 20150813, but @Maximus5 minhook patch appears to work here as well.

**Comment by narnaud** [comment]
I also tested ConEmu 20150816 and @Maximus5 minhook version, and it's working nicely.
+1 from me too

**Comment by mridgers** [comment]
On the surface it may appear to work but in actual fact there is a subtle flaw. As Clink never calls the original ReadConsoleW function (it doesn't need to) it means that ConEmu's hook is skipped completely and whatever OnReadConsoleW does is never executed. I do not know what the impact of that is but I imagine there is a risk it will cause subtle bugs in ConEmu.

**Comment by Maximus5** [comment]
Thanks for the note, I will recheck this case.

**Comment by mindw** [comment]
Any news on this one?

Thanks!

**Comment by paulbombarde** [comment]
Updated both ConEmu and Clink today. Seems to still work perfectly in my setup.

**Comment by mridgers** [comment]
0.4.8 works fine with ConEmu v160710 for me.
