### ISSUE TITLE
History expansion is performed inside double quotes

### ISSUE THREAD

**Issue by jtnord** [mridgers/clink#343]
History expansion is performed for an `!` when used inside a double quoted string which is IMO wrong.
even if it was correct it produces the wrong results!

```
C:\workarea\source\cloudbees\cjp-champagne-lib>echo 1234556
1234556

C:\workarea\source\cloudbees\cjp-champagne-lib>echo "hello!"
History expansion: echo "hello"c:\Program Files (x86)\clink\0.4.4\clink.bat" /k cd cloudbees-aborted-builds\
"hello"c:\Program Files (x86)\clink\0.4.4\clink.bat" /k cd cloudbees-aborted-builds\
```

compared with bash on Linux
```
user1@linux-slave:~$ echo 21134234234
21134234234
user1@linux-slave:~$ echo "hello!"
hello!
```

**Comment by mridgers** [comment]
Yup, it is pretty annoying but thankfully reported already in #317 and has been fixed. 0.4.5 is days away and that will introduce a "history_expand_mode" setting that controls this behaviour (it defaults to ignoring `!` characters in single and double quotes)
