### ISSUE TITLE
clink 0.45 does not expand environment variables in doskey macros if they loaded via doskey /MACROFILE...

### ISSUE THREAD

**Issue by gkruschina** [mridgers/clink#344]
clink 0.45 does not expand environment variables in doskey macros if they loaded via doskey /MACROFILE...

You can check this by a simple test:
Create a file "doskey.txt" with the content:
mynotepad="%WINDIR%\notepad.exe"

And a file "startup.cmd" with the content:
doskey /MACROFILE=doskey.txt

Copy these two files in the the extracted "clink_0.4.5.zip" and call clink.bat.
Afterwards run "startup.cmd" and then the doskey macro "mynotepad".

Then you will get an error message: FILE NOTE FOUND.
This works without any problems with clink 0.44.

**Comment by VictorVG** [comment]
Added - this bug exists on v0.44 - lua:

```
local hunspell=ffi.load("hunspell"..(win.GetEnv("PROCESSOR_ARCHITECTURE"):gsub("AMD64","x64")))
```
and result's:

![luafar](https://cloud.githubusercontent.com/assets/906886/9645440/4ec0b13c-51d4-11e5-800e-3ab8336429d9.png)
