### ISSUE TITLE
The Ctrl+Z cause some text remain on screen

### ISSUE THREAD

**Issue by doggy8088** [mridgers/clink#346]
When I using Cmder, I met this problem long time ago.  When I paste a text with Ctrl+V onto the Console, then press Ctrl+Z (undo).  The first character will remain on screen.  Here is the steps to reproduce this problem.

1. Open cmder window (Command prompt)
![image](https://cloud.githubusercontent.com/assets/88981/9657827/1932f4a0-5277-11e5-9921-378f9348a144.png)

2. Paste a text on it.  For example, `http://cmder.net/`
![image](https://cloud.githubusercontent.com/assets/88981/9657833/212dd526-5277-11e5-9c47-7630b569f3f8.png)

3. Then press Ctrl+Z undo changes.  You'll see "h" remain on window and the "h" can't be deleted unless you clear the screen by "Ctrl+L".
![image](https://cloud.githubusercontent.com/assets/88981/9657839/2f689810-5277-11e5-9757-d3c240277528.png)

4. If you just paste the same text again.  The screen will like the following screenshot.
![image](https://cloud.githubusercontent.com/assets/88981/9657844/420f9900-5277-11e5-93d7-eb4528e7f155.png)

**Comment by uahim** [comment]
hit Ctrl+Z again? :) but seriously, I can confirm this happening in pure cmd.exe, apparently it deletes portions of text rather than the entire pasted/typed string. but maybe it's a feature rather than a bug?

**Comment by doggy8088** [comment]
@uahim I tried. Hit Ctrl+Z multiple times doesn't solve the problem.  Also, the pure cmd.exe doesn't have a "Ctrl+Z" (undo) feature.  I don't understand what do you mean about "maybe it's a feature rather than a bug" ?

**Comment by doggy8088** [comment]
I recorded a short video to show this problem.  Please check: https://youtu.be/sQ5ZURcAi5Q

**Comment by uahim** [comment]
@doggy8088 sorry, I chose my words poorly: by "pure cmd" I meant it also happens in clink+cmd rather than clink+cmder, of course; and *in clink+cmd this behavior can be reproduced*, but can be worked around with simply repeating the shortcut (which indeed is a little annoying).

with the last sentence I meant maybe it is the way the authoer intended it to be or it may be depending on readline.

**Comment by doggy8088** [comment]
@uahim I tried to use clink+cmd that is ok.  It may not a problem from clink or readline.  I'm not sure.  Is it possible a Cmder problem?

**Comment by doggy8088** [comment]
I find out the root cause finally.  I think this problem is not related to clink.  My workaround was noted here: https://github.com/cmderdev/cmder/issues/623

**Comment by uahim** [comment]
interesting. as I said I'm not using cmder, but I experience the same behavior. when I paste `https://github.com/mridgers/clink/issues/346`, I need to hit Ctrl+Z thrice: it first deletes "/346", then "ridgers/clink/issues" and the last time it deletes the rest.

this is reproducable in multiple/new cmd windows.

**Comment by matreex** [comment]
#623
update to v1.3.0, edit ~\cmder\vendo\init.bat, search the keywords: `**_@prompt_**`, but don't find it, so... add `_**@prompt $E[1;32;40m$P$S $S$_$E[1;30;40m$$ $E[0m**_` to init.bat, but the code is not working, what i do for this?

it's bug? Just like that.
<a href="http://imgur.com/a/VlKdv"><img style="max-width:100%;" src=http://i.imgur.com/s6UTOvE.png"></a>
