### ISSUE TITLE
Line Editing broken on almost-full Line

### ISSUE THREAD

**Issue by markusgritsch** [mridgers/clink#347]
*) Fill the currently line almost completely up, so that just the last column stays empty.
*) Place the cursor somewhere inside the last word.
*) Enter one character -> the cursor jumps to a wrong location, entering another character inserts the character at a wrong position and the cursor jumps again.

Example:
![1](https://cloud.githubusercontent.com/assets/2684183/9791094/acae83f4-57d9-11e5-9792-bcf7a091174d.png)
now place the cursor between 3 and 4 and enter zz:
![2](https://cloud.githubusercontent.com/assets/2684183/9791128/d58f7968-57d9-11e5-9f08-3306f7c34aac.png)

**Comment by Stanzilla** [comment]
Oh yeah, noticed that just recently, too.

**Comment by Stanzilla** [comment]
@mridgers Yay! Do you have plans to make a new test build available?

**Comment by mridgers** [comment]
Yup, there is one [here](https://www.dropbox.com/sh/e3fucpdjbcjd5d9/AACbC9I8hMDbVV_W0vDnxU36a?dl=0).

**Comment by narnaud** [comment]
Do you plan to create a release? it's quite a nasty problem and the test build is fixing it nicely,

**Comment by mridgers** [comment]
[Done](https://github.com/mridgers/clink/releases/tag/0.4.6).

**Comment by narnaud** [comment]
@mridgers Great, thank you

**Comment by markusgritsch** [comment]
Hmm, the new release is not usable in ConEmu: Pressing the cursor keys inserts strange characters instead of moving the cursor around :(  I've reverted to the dev-version from the dropbox link.

**Comment by mridgers** [comment]
Odd, as I tested Clink with ConEmu extensively. I've just got [ConEmu v151224 (portable)](http://www.fosshub.com/ConEmu.html) and everything is working fine for me - both manually starting Clink or by dropping the files into `ConEmu/clink`.

**Comment by markusgritsch** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/2684183/12049984/de07a6e4-aeee-11e5-8565-e266e8d437fd.PNG)

Here is what it looks like pressing the cursor keys LEFT LEFT LEFT LEFT UP UP UP UP RIGHT RIGHT RIGHT RIGHT DOWN DOWN DOWN DOWN.

I use the x64 installed version of ConEmu (also latest version).  Please find my ConEmu settings here:
[ConEmu.zip](https://github.com/mridgers/clink/files/74790/ConEmu.zip)

**Comment by mridgers** [comment]
Still working fine. Do you have an `_inputrc` or `.inputrc` file in %home% or %userprofile% by any chance?

**Comment by markusgritsch** [comment]
Indeed, I found an .inputrc file dated from 2004 located in %HOME%, which was the culprit.
[.inputrc.zip](https://github.com/mridgers/clink/files/75115/default.inputrc.zip)

After renaming it to something else, clink works fine again. Thanks!
