### ISSUE TITLE
clink autorun value arguments

### ISSUE THREAD

**Issue by Pajamaman** [mridgers/clink#348]
I can't figure out the correct syntax to use for the autorun verb:

```cmd
C:\Users\Pajamaman>clink autorun show

Current AutoRun values

  Current user:

    native : "C:\clink\clink" inject
     wow64 : "C:\clink\clink" inject

  All users:

    native : <unset>
     wow64 : <unset>

C:\Users\Pajamaman>clink autorun value "C:\clink\clink inject"
ERROR: Invalid arguments. Run 'clink autorun --help' for info.

C:\Users\Pajamaman>clink autorun value "C:\clink\clink" inject
ERROR: Invalid arguments. Run 'clink autorun --help' for info.

C:\Users\Pajamaman>clink autorun value "C:\clink\clink" -- inject
ERROR: Invalid arguments. Run 'clink autorun --help' for info.
```

Based on the output of `autorun --help` I would expect the first attempt to be the correct one.

What I'd really like is to set the autorun value to `"C:\clink\clink" inject --quiet`, but I can't even get the first part working.

**Comment by mridgers** [comment]
I changed it to "set" (which I felt was more intuitive compared to "value") but I forgot to update the "--help" text! Try this; `clink autorun set "c:\clink\clink inject"`.

I've fixed the incorrect help text and made it clear what `autorun` does.

**Comment by Pajamaman** [comment]
Great, thanks!
