### ISSUE TITLE
Using "cd -" under clink

### ISSUE THREAD

**Issue by andalou** [mridgers/clink#349]
Under bash, if I want to return to the original directory with "cd", I can use:
cd -
Isn't there anything similar with clink?

Many thanks in advance,

Cesar

**Comment by mridgers** [comment]
Clink can't do this as it only concerns itself with replacing cmd.exe's line editing and not with adding new behaviour to cmd.exe's interpretor. Take a look at #350 which is similar and has some suggestions on ways this could be emulated.
