### ISSUE TITLE
How to use `~` as a home directory

### ISSUE THREAD

**Issue by doggy8088** [mridgers/clink#350]
In Linux environment, I can use `cd ~` to enter user's home directory.  In Windows, I have to use `cd /d %userprofile%`.  Is it possible to do any setup that allow us to use `cd ~` in clink to enteing into user's home directory in Windows?

**Comment by mridgers** [comment]
Clink can't do this as it only concerns itself with replacing cmd.exe's line editing and not with adding new behaviour to cmd.exe interpretor. Perhaps https://github.com/wting/autojump would be useful? Another option is to use `Alt-Shift-~` to expand the `~`, or add a macro to your `clink_inputrc`; e.g. `"\C-x\C-h": "\C-ucd /d ~M-~^M"` (this will type `cd /d ~`, expand the `~`, and execute the line when you press `Ctrl-x Ctrl-h` key sequence.
