### ISSUE TITLE
Crash in 32-bit Windows 7

### ISSUE THREAD

**Issue by shr1k** [mridgers/clink#351]
clink (x86, 0.4.4 and 0.4.5) keeps crashing in in Windows 7 32-bit setup. I'm not exactly sure why -- is there someplace I can investigate a crash log or some such? The Window event log only shows this information:

> Faulting application name: cmd.exe, version: 6.1.7601.17514, time stamp: 0x4ce78e2b
> Faulting module name: clink_dll_x86.dll, version: 0.4.5.25585, time stamp: 0x55e341fb
> Exception code: 0xc0000005
> Fault offset: 0x0002ff06
> Faulting process id: 0x2b9c
> Faulting application start time: 0x01d0f7aa093f83cd
> Faulting application path: C:\Windows\system32\cmd.exe
> Faulting module path: C:\tools\clink_0.4.5\clink_dll_x86.dll
> Report Id: 47e8fb66-639d-11e5-9692-00a0c6000000

Also attached is a screenshot of the issue.

What other details can I provide with hunting this issue down?

Cheers,
Shrikant

![clinkissue](https://cloud.githubusercontent.com/assets/927606/10105375/49f4551c-63a6-11e5-98e7-1baf050e5781.png)

**Comment by VictorVG** [comment]
Version 0.43 CMD drop, but there were mistakes and to upgrade to v0.44 -> v0.45 eventually I did clink demolished because of problems caused by it in the console. Requirement history in Far Manager v3.0, and Lua scripts (I have "only" a hundred, in which about 230 macros with a dozen other hotkeys, but the clink was convenient in terms of working with the same GCC / MS VC ++ SDK - remember that I have not had to look for the desired entry in the hundreds in history.db Far-well, although you can run over numbers, because any debris so tries to get into the story, and each time to write your own script for her and put it in on everyone Far .HistoryDisabled ()? :)

**Comment by shr1k** [comment]
@VictorVG: I'm sorry, I didn't undertand what you're trying to say. Should I roll back to version 0.4.3 and try again..?

**Comment by VictorVG** [comment]
Yes, it is worth a try, but personally I do not want to experiment. Too many mistakes after the experiments should be eliminated.

**Comment by mridgers** [comment]
I have absolutely no idea what's going on here. @shr1k, did you happen to get a copy of the mini-dump file for the cmd.exe that crashed? I think Windows should create them somewhere. A mini-dump file will hold all the clues as to what has caused Clink to segfault and crash cmd.exe.

**Comment by VictorVG** [comment]
**@mridgers**

I think in addition to find the cause of failure can help you [**Process Hacker v2.37 r6242 DEV**](https://yadi.sk/d/193Gnglm4Ia5D). The only thing that should not be used in the absence of MS Visual Sudio is the debugger - Microsoft tried. But the stack, thread, data handles, windows, memory modules, network monitoring and security tokens during installation (processhacker-2.37-setup.exe takes into account that while some plugins plugins-extra group are at an early stage of development and does not put them on the OS newer Win7. And therefore it is better to use for the installation and access to the operating system kernel data structures necessary to install the driver KProcessHacker - features of the PH working through Native API bypassing ntdll.dll) .Otdat team to create a mini-dump operator can via the context menu RN - this tool there just is).

**Comment by shr1k** [comment]
@mridgers: I've generated a minidump file and [uploaded it here](https://www.dropbox.com/s/u5f18wymgn46qlr/cmd.exe.13428.dmp?dl=0).

**Comment by mridgers** [comment]
@shr1k Thanks, that minidump works perfectly. One more thing that would be useful is to know what's in the `clink.log` file (in `C:\users\...\appdata\local\clink`).

@VictorVG Thank you for the tips. I have everything I need now that a minidump has been provided.

**Comment by VictorVG** [comment]
Please. :)

**Comment by shr1k** [comment]
@mridgers: Oops, not sure why Github isn't delivering notifications, but here's the contents of clink.log:

```
13576 do_inject                  185 System: ver=6.1 1.0 arch=0 cpus=4 cpu_type=586 page_size=4096
13576 do_inject                  190 Version: 0.4.5
13576 do_inject                  191 DLL: C:\tools\clink_0.4.5\clink_dll_x86.dll
13576 do_inject                  193 Parent pid: 13428
13576 check_dll_version           52 DLL version: 00000004 000563f1
13576 do_inject_impl             283 Creating remote thread at 7798DD65 with parameter 00560000
13428 set_rl_readline_name        58 Setting rl_readline_name to 'cmd.exe'
13428 hook_trap_veh              120 VEH hit - caller is 49F92094.
13428 hook_jmp                   408 Attemping jump hook.
13428 hook_jmp                   409 Target is kernel32.dll, ReadConsoleW @ 779A27EE
13428 hook_jmp_impl              351 Attempting to hook at 779A27EE with 0F4053B8
13428 get_instruction_length     316 Matched prolog 8B55FF8B (mask = 0000FFFF)
13428 hook_jmp                   419 Success!
13428 hook_iat                    77 Attempting to hook IAT for module 0F400000
13428 hook_iat                    78 Target is (null),ReadConsoleW (by_name=1)
13428 iterate_imports             94 Checking imports in 'dbghelp.dll'
13428 iterate_imports             94 Checking imports in 'KERNEL32.dll'
13428 hook_iat                   104 Found import at 0F457108 (value = 779A27EE)
13428 hook_iat                    77 Attempting to hook IAT for module 49F90000
13428 hook_iat                    78 Target is (null),WriteConsoleW (by_name=1)
```

That's all was in there.

**Comment by mridgers** [comment]
Thanks.

**Comment by shr1k** [comment]
Sorry to be a pain, but have you been able to find out what's causing this?

Cheers.

**Comment by keke9036** [comment]
Powercmd throws same error when integrating with clink~

**Comment by shr1k** [comment]
Thanks for the fix! I'm no longer using Windows for development (at long last..) so I'm unable to confirm, but appreciate your work all the same :)
