### ISSUE TITLE
Tab completion with options gathered from a program

### ISSUE THREAD

**Issue by promisedlandt** [mridgers/clink#353]
Hello,

instead of manually writing a completion file, I would like to have my program return the completion options.

In bash, I can do that with a simple script like this:
````shell
{
  local cur prev opts
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  opts=$( ${COMP_WORDS[@]:0:$COMP_CWORD} --bash-completion )
  COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )

  return 0
}
````

Is there any way to duplicate this behaviour in clink?

**Comment by mridgers** [comment]
Nice idea. How does Bash differentiate between the different styles of options (i.e. `--foobar`, `-f`, and `/Windows`)? Does it do anything special if this optional arguments take parameters such as paths?

**Comment by promisedlandt** [comment]
I'm pretty sure bash does differentiate between them at all, and it's up to the program or the completion script to handle anything like that.
All you can do in a script is create an array with possible matches for the entered command. Bash then takes care of matching the already entered partial command to what's in that array (either completing it or displaying the completion options).
So it would be up to my command to handle the flags correctly and return the correct completion options for `asdf --force`, `asdf -f` and `asdf /force`.

**Comment by mridgers** [comment]
I wonder if I may have misunderstood something here actually. Are you aware that it is possible to use Lua to extend and customise tab-completion in Clink (details in `clink.html` and [here](https://github.com/mridgers/clink/blob/master/docs/clink.md#extending-clink))?

**Comment by promisedlandt** [comment]
I had read the documentation, but either I misunderstood it or what I mean is not possible.
Giving specific examples should make sure we're talking about the same thing, right?

I have an application called `d4t` (a tool for managing play by email turns for a game), and that application has a few subcommands (just like git).
So, first thing, I want to autocomplete these, e.g.:
`d4t r<tab>` can expand to `d4t replay` or `d4t restore`.
This is very simple, and could be done in clink by hardcoding. But then I need to manually update the syntax completion file when I add a new subcommand, and I don't want to do that.
In the bash script I  just call `d4t --bash-completion` and it returns an array of all subcommands - I just need to add them in the program, and the completion script never changes.

The second, and more complicated, use case is that some of the subcommands accept game names, and I want to autocomplete these. Getting the game names happens during run time, and can't easily be moved to a completion script (requires reading a config file / command line flags).
For example, the `restore` subcommand takes a game name, you would call it like `d4t restore examplegame`. If you were to type `d4t restore ex<tab>`, I want to autocomplete that as well.
In the bash script, that would call `d4t restore --bash-completion`, which then returns an array of all game names.

Unless I misread the docs, that is currently not possible with clinks?

**Comment by Stanzilla** [comment]
@promisedlandt Sure is, see the link mridgers gave you.

**Comment by promisedlandt** [comment]
Thank you. I guess I need to read it a couple more times then :)
