### ISSUE TITLE
% expansion in aliases don't work

### ISSUE THREAD

**Issue by samlh** [mridgers/clink#361]
If you create an alias which references a non-existent environment variable, and later set the environment variable, the alias doesn't work with clink.

    echo >c:\Foo\bar.cmd
    alias baz %foodir%\bar.cmd
    set foodir=c:\Foo
    baz

This broke in v0.4.5

**Comment by variab1e** [comment]
I've found this as well.

**Comment by ArkBrj** [comment]
Expansion does not work even if environment variable exists.
Try the following in a cmd window with and without clink injected:

set foo=c:\Windows
doskey bar=cd ^%foo^%
bar

In the pure cmd window the result is that the current directory becomes c:\Windows.
If clink is injected, executing "bar" results in "The system cannot find the path specified."

**Comment by sgrebnov** [comment]
same issue

**Comment by mridgers** [comment]
This was fixed in 17b807c6 (for #344).
