### ISSUE TITLE
ClamAV sees Clink installer as trojan

### ISSUE THREAD

**Issue by Spaghetti-Cat** [mridgers/clink#363]
Anti-virus ClamAV with virus database version 21066 [finds](https://www.virustotal.com/de/file/3b8bc5d6a6c26ff6011bf9428a8473958e8c3d0ecb3bdffae5b1b48fe3970bfd/analysis/1447839109/) a "Win.Trojan.Win32-2" when scanning `clink_0.4.5_setup.exe`.

You can see in the link that no other virus scanners find a problem.

**Comment by mridgers** [comment]
VirusTotal's version of ClamAV isn't reporting any issues with v0.4.6;

[clink_0.4.6_setup.exe](https://www.virustotal.com/en/file/a1500257afd6e5728368a1d24f3ba62323fe482f40a63f081e1b8b1a16f69398/analysis/1451466693/)
[clink_x64.exe](https://www.virustotal.com/en/file/298e7106112f799e6d6de17cc93ec0060ac8188340fa9a6fe979a8aba75c14bc/analysis/1451466928/)
[clink_x86.exe](https://www.virustotal.com/en/file/e23373b46fbaf76e0216adbed4472f3968b1439bd07374c42547efc5614fafec/analysis/1451466991/)
[clink_dll_x64.dll](https://www.virustotal.com/en/file/52cc06a31e74d6488dc0292be8aad1799a37624dee7d2ba7014a52e948cadc0a/analysis/1451467088/)
[clink_dll_x86.dll](https://www.virustotal.com/en/file/07fdef4e9345738553a19079d7464060501acb65fc74e429db0c35fe251b0f96/analysis/1451467159/)
