### ISSUE TITLE
Launching Clink with a command from a shorcut

### ISSUE THREAD

**Issue by Gettyk** [mridgers/clink#364]
I used to launch cmd via a shorcut icon on desktop for which I modify the target . This enable me to launch a command with a simple click. 

The target I used for cmd is : `%windir%\system32\cmd.exe /k python c:\gsutil\gsutil -m cp -r -n Loop gs://Bucket/Loop`

I use Clink without installing it, directly from the bat in the zip.  I created a shorcut icon on desktop that link to the bat. The target of this shorcut is thus : `"C:\Users\Computer\Desktop\programs\clink_0.4.5\clink.bat"`

I tried to set this target to : `"C:\Users\Computer\Desktop\programs\clink_0.4.5\clink.bat /k python c:\gsutil\gsutil -m cp -r -n Loop gs://Bucket/Loop"` but it doesn't work (I can't even save the changes. 

So here is my question : Is there a way to start a command in Clink directly from a shorcut icon?

**Comment by mridgers** [comment]
You can set your shortcut to something like this; `cmd.exe /s /k "python myscript.py & call "c:\path\to\clink\clink.bat" inject"` or run `clink autorun install` once.

**Comment by Gettyk** [comment]
Thanks!
