### ISSUE TITLE
Ctrl+C from running .bat causing crash

### ISSUE THREAD

**Issue by costin** [mridgers/clink#366]
I'm starting a .bat file which creates a process that keeps on waiting. On Ctrl+C, the console crashes and the following [mini_dump.dmp](https://www.dropbox.com/s/kgr2n9tuimv84d5/mini_dump.dmp?dl=0) is created.

Using clink v0.4.5 on Win 8.1 x64 update (with the latest updates installed).

**Comment by mridgers** [comment]
Thanks for forwarding the mini_dump.dmp - it was very useful in determining what I think had happened. Hopefully it's now fixed!

**Comment by costin** [comment]
Cheers! Will report back if the issue occurs in v0.4.6.
