### ISSUE TITLE
PageDown and PageUp

### ISSUE THREAD

**Issue by limeb** [mridgers/clink#370]
Is there a way to get the PageDown and PageUp keys to work correctly?

**Comment by limeblack** [comment]
The following autohotkey script fixes it somewhat 

    #IfWinActive ahk_class ConsoleWindowClass
      PgDn::Send {Alt Down}{Space}{e}{l}{Alt Up}{PgDn}
      PgUp::Send {Alt Down}{Space}{e}{l}{Alt Up}{PgUp}
    #IfWinActive

**Comment by mridgers** [comment]
What do you mean by "work correctly"? Are you referring to the same thing raised in #365?

**Comment by limeblack** [comment]
@mridgers I would prefer not to have to enter scroll mode before hitting page down and page up similar to how cygwin works on Windows.

**Comment by mridgers** [comment]
Ah, I see. You want PgUp/PgDn to scroll the console buffer? Clink binds Shift-[PgUp|PgDn] for this, chosen because that's a common binding for scrolling Linux terminals.
