### ISSUE TITLE
Autoruns complains

### ISSUE THREAD

**Issue by UweKeim** [mridgers/clink#374]
[Autoruns](https://technet.microsoft.com/en-us/sysinternals/bb963902.aspx) complains:

> File not found: C:\Program Files (x86)\clink\0.4.6\clink.exe		

I guess this is because the entry in the registry omits the file extension:

> "C:\Program Files (x86)\clink\0.4.6\clink" inject --profile ~\clink

and actually points to a BAT file, rather than an EXE file.

**My suggestion:**

Add the ".bat" extension to the registry entry.

**Comment by mridgers** [comment]
Thanks!
