### ISSUE TITLE
fish style completion

### ISSUE THREAD

**Issue by alexezh** [mridgers/clink#379]
Hi,

Is there any way to do fish style completion where I can see result from history as soon as I start typing? 

If this is not possible, is there a way to get history match based on current data I typed? In other words I typed "xyz" and I want to see history matches for xyz

**Comment by mridgers** [comment]
I'd love that. Completion in Clink is simply what Readline provides but I think there's better choices to tab-key driven, lowest-common-denominator completion. Behind the scenes I've been chipping away at some tests along these lines - fuzzy incremental completion, meta-data and coloured match display, among other things. These things take time to come to fruition though, especially as plenty of folks are happy with Readline's style of completion.

**Comment by AntonioRedondo** [comment]
It's a pity history partial completion isn't implemented on Clink. It doesn't have to be as fancy as the one on Fish shell. No need for colours and instant background hint completion.

It would be perfect like it's done on Bash. For example, if in the terminal is written
```
npm
```
and the key <kbd>↑</kbd> is pressed, the history only will iterate over entries that start by `npm`:
```
npm i
npm list
npm view
```

However, with Clink, what it's already written on the terminal will be ignored and when pressing <kbd>↑</kbd> history will iterate over all entries in reverse chronological order.
```
npm i
git status
ls -la
npm list
```

Even PowerShell has history partial completion by pressing <kbd>F8</kbd> to iterate over the history entries matching the text typed and then select the entry wanted with <kbd>Enter</kbd>. This implementation is overcomplicated and worse –in my opinion– than just pressing <kbd>↑</kbd> like on Bash. But well, at least is something.

**Comment by AntonioRedondo** [comment]
So I just discovered that history partial completion is implemented with the key combination <kbd>Ctrl</kbd>+<kbd>PgUp</kbd> or <kbd>Ctrl</kbd>+<kbd>PgDown</kbd>.
