### ISSUE TITLE
double click on batch -> clink is not injected

### ISSUE THREAD

**Issue by schlamar** [mridgers/clink#383]
When I double click on a Batch file in Windows explorer, clink is not injected. So Ctrl+C is not auto-answered and prompt modifications with color do not work.

**Comment by mridgers** [comment]
This is because Windows launches double-clicked Batch files like this; `cmd.exe /c foobar.bat [args...]`. The `/c` means the `cmd.exe` process isn't interactive so Clink doesn't inject itself into it. You can try adding this to the top of your .bat script as a way to overcome this;

```
if "%1"=="" ( start "test" cmd.exe /k %0 foobar & exit /b 0 )
```
