### ISSUE TITLE
(in ConEmu) Text flow to next line broken when using ESC]9;8; or ESC]9;3; in prompt

### ISSUE THREAD

**Issue by eugenesvk** [mridgers/clink#384]
When I enable clink in **ConEmu** I get a weird bug where text reflow stops working for some prompts (instead of going to the 2nd line text just overwrites the first line). More detailed description with screenshots is @ https://github.com/Maximus5/ConEmu/issues/563
ConEmu works fine as is without Clink enabled.
Any idea what's causing this and how to fix it?

**Updated** to include another sequence `ESC]9;3;`, which I'm using to change tab title in ConEmu to reflect current folder with some adjustments (e.g. showing `~` instead of `%USERPROFILE%` path, which I can't do if I use default ConEmu settings)

Using latest version of Clink v0.4.7 installed in default ConEmu 160228 [32] on a Windows 10.0.10586

**Comment by Maximus5** [comment]
Looks like clink must take into account [ANSI OSC sequences](https://conemu.github.io/en/AnsiEscapeCodes.html#OSC_Operating_system_commands). It does not relate only to ConEmu-specific codes.

**Comment by robi-wan** [comment]
Related issue: Maximus5/ConEmu#585

**Comment by cs96and** [comment]
Is there any plan to release v0.4.8 with this fix included?  It's driving me mad!

**Comment by cs96and** [comment]
I'm still waiting for a new version... when will it be ready?  Thanks.

**Comment by Stanzilla** [comment]
@mridgers is on vacation at the moment, he told me via Twitter. :)

**Comment by mridgers** [comment]
0.4.8 is published now. Apologies for the delay.
