### ISSUE TITLE
Add errorlevel into clink Lua API for prompts

### ISSUE THREAD

**Issue by eugenesvk** [mridgers/clink#385]
This issue https://github.com/mridgers/clink/issues/83 indicates a workaround is possible, but doesn't explain how to implement it.
Would you please specify how I can

> add %errorlevel% to the prompt and extract if from the path passed in to calls to your prompt filter.

**Comment by mridgers** [comment]
Something like this should do it;

```lua
local function filter()
    local error_level = clink.get_env("=ExitCode")
    clink.prompt.value = "[" .. error_level .. "] " .. clink.prompt.value
    return true
end

clink.prompt.register_filter(filter, 1)
```

`cmd.exe` doesn't always set the `=ExitCode` environment variable, and it's a hexadecimal string so a little bit of post-processing will be in order.

**Comment by eugenesvk** [comment]
Thank you, that's at least something, even though you're correct that it's not always set like for %ERRORLEVEL%.
By the way, which command would write TO the env variable? I just want to reset "=ExitCode" after I've read it for the first prompt display so it doesn't affect all subsequent prompt displays.
Is there something like `clink.set_env`?

**Comment by ferenczy** [comment]
Where's the environment variable `=ExitCode` coming from? And what the prefix `=` means? I wasn't able to find any information regarding that.

Anyway, it seems to be working fine for me so far. In what cases it's not working?

**Comment by ferenczy** [comment]
So it's not working very well. The environment variable `=ExitCode` is being set only sometimes, for example, a batch script calling `exit /b 1` won't set it (it properly sets the environment variable `%ErrorLevel%` but I didn't manage to get its value in Clink's Lua scripts so far).

Also, `=ExitCode` is not being reset (and I didn't find any way to do it explicitly so far), so until some command will set it again, you'll be getting an old value. And many standard programs won't set it (e.g. `echo`, `start`, etc.). Some programs which set it properly are for example `sc` or `wmic`.

So it's not very usable currently, unfortunately.
