### ISSUE TITLE
Git alias auto complete

### ISSUE THREAD

**Issue by lijunle** [mridgers/clink#386]
Hi, 

Thanks for making such a great tool. It is amazing!

The git auto complete works great, however if I make `co` as alias of `checkout`, the auto complete for branch names not works. Could you please support this?

**Comment by mridgers** [comment]
I think you're after @vladimir-kotikov. He has put together the excellent completion for Git over at [clink-completions](https://github.com/vladimir-kotikov/clink-completions)
