### ISSUE TITLE
clink.set_console_aliases()

### ISSUE THREAD

**Issue by prabirshrestha** [mridgers/clink#388]
Is there a way to set console alias everytime clink starts?
For example I want to set `g` to refer to `git`.

Currently the only api I see is `clink.get_console_alias()`
https://github.com/mridgers/clink/blob/master/docs/api.md#clinkget_console_aliases

**Comment by mridgers** [comment]
Not via clink but you can do this using Doskey, which is just a front-end for the Windows console's alias support. Try this;

```
c:\>doskey g=git $*
c:\>g --version
```

You can wrap this up in a Batch script if you wanted to, and start your command prompt through that instead;

```
@if "%1"=="" ( start "test" cmd.exe /k %0 foobar & exit /b 0 )
doskey g=git $*
```

Add a shortcut to this .batch file and assign a key-combo to the shotcut for fast starting of your command prompts.

**Comment by ankostis** [comment]
But sin't there any other way to auto-launch this batch file on startup, without user intervention?
