### ISSUE TITLE
detect clink / ANSI support in batch file

### ISSUE THREAD

**Issue by schlamar** [mridgers/clink#389]
Is there a way to detect if clink has been loaded? I want to know if ANSI escape sequences (`$E[...`) will work or not.

**Comment by mridgers** [comment]
You could use the Doskey macro that Clink sets like this;

```Batch
doskey /macros|find "clink" /i /c 1>nul
if errorlevel 0 echo Clink is loaded
```

Or if you want a more complex way that doesn't involve relying on a doskey macro being set you can use `tasklist.exe` to identify process with Clink's DLL loaded;

```Batch
:: Set the title of this cmd.exe window so we can use tasklist to get it's PID.
set x="%random%"
title %x%
for /f "tokens=2 delims=," %%d in ('tasklist /v /fo csv^|find %x%') do (
    set pid=%%d
)

:: List all processes with Clink loaded and match the PID
for /f %%d in ('if defined pid tasklist /m clink_dll_x64.dll^|find %pid% /c') do (
    if %%d == 1 echo Clink loaded
)
```

**Comment by schlamar** [comment]
Your test is wrong. `if errorlevel 0` always holds true because this compares `%errorlevel% >= 0`. 

But it works with `if errorlevel 1`:

    set CLINK=1
    doskey /macros|find "clink" /i /c 1>nul
    if errorlevel 1 set CLINK=

    if defined CLINK (
        echo Clink is loaded
    ) else (
        echo Clink is not loaded
    )
