### ISSUE TITLE
Set custom profile location by env var

### ISSUE THREAD

**Issue by eugenesvk** [mridgers/clink#390]
I'm using [ConEmu](https://github.com/Maximus5/ConEmu) and would like to store all my settings in one folder. The simplest way to enable clink in ConEmu is to click `Use clink in prompt` in settings. However, this prevents me from using `--profile <path>`.
Can you please add an option to read profile path from environment variable so that I can set it once in ConEmu and point to the path I want and not worry about having to add the injection script with custom path myself for every cmd.exe task I'm using?
Thank you

**Comment by eugenesvk** [comment]
Thank you! Can confirm this is working

**Comment by mridgers** [comment]
Good to hear. Thanks for testing the change.
