### ISSUE TITLE
Directory name completion cannot see one directory - Mozy Sync?

### ISSUE THREAD

**Issue by libove** [mridgers/clink#394]
I just noticed that Clink cannot perform Directory name completion on just one directory, which happens to be a Mozy Sync directory.

This is on Windows 7, 64-bit (SP1, all patches, etc).
CMD ver 6.1.7601.
Clink ver 0.4.7.

The directory in question happens to be on a File Share from a Windows Server 2012R2, but the Mozy Sync is running locally on this Windows 7 workstation.

The parent directory has some **216** files and directories in it (according to Clink TAB TAB completion). 
However, piping DIR through WC -L (love my Cygwin...) and removing the headers and footers shows **217** files and directories. The one that is missing (Clink DIR TAB TAB, yes, look at whole list) is exactly the Mozy sync directory.

So, is there something about Mozy Sync which breaks Clink's directory name completion feature?

thanks.

**Comment by mridgers** [comment]
The only type of entries that I would expect to not show up are directories with the system attribute set. The only think I can think of is that the Mozy Sync folder isn't actually a folder but a link or some other feature of the NTFS file system. How does it's entry look when `dir` lists it? Does it show up if you do `dir /ad`?

**Comment by libove** [comment]
Hi Martin,
Yes, that Mozy Sync directory appears in a DIR list, looking just the same as all of the other subdirectories, e.g.: 
![mozy dir for github](https://cloud.githubusercontent.com/assets/2027232/14766041/24049770-09fc-11e6-9f39-0003c254f63d.jpg)

Aha, indeed, the System attribute is set.
> U:\doc> ATTRIB "MozySync-J&Y"
>    S     U:\doc\MozySync-J&Y

So, why should System-attribute directories NOT appear in the Directory name completions?

**Comment by mridgers** [comment]
It's pretty normal through out Windows to not list system files and Clink follows that pattern. It's a hard-coded behaviour in this instance. I'd say it's much better to change the MozySync folder's attributes in this instance personally.
