### ISSUE TITLE
Forward slashes in path completion

### ISSUE THREAD

**Issue by modbw** [mridgers/clink#395]
Would it be possible to have (optional) forward slashes in path completion? As I copy/past paths from a clink pimped cmd to a ssh session from time to time this would be really practical for me.

**Comment by mridgers** [comment]
Optionally isn't quite so straight forward, but you can do it by creating a dummy Lua match generator that tells Clink to use forward slashes. Put this in a .lua file alongside Clink;

```lua
local function force_fwd_slashes(text, first, last)
    clink.slash_translation(1)
    return false
end

clink.register_match_generator(force_fwd_slashes, -1)
```

**Comment by keathmilligan** [comment]
Nice - if you use [cmder](http://cmder.net/), you can just add this to the end of your cmder/config/cmd.lua file and it works.

**Comment by oussaka** [comment]
It is good for me
Thanks, bro
