### ISSUE TITLE
Clink bundled with Cmder sets title to "npm"

### ISSUE THREAD

**Issue by Daniel15** [mridgers/clink#397]
Cross-posting from https://github.com/cmderdev/cmder/issues/933 as I'm not sure whether this is a Cmder issue or a Clink issue.

To repro:
1. Download Cmder and extract to `c:\apps\cmder`
2. Open `cmd`
3. Run:
```
set CMDER_ROOT=c:\apps\cmder
"%CMDER_ROOT%\vendor\clink\clink_x64.exe" inject --quiet --profile "%CMDER_ROOT%\config"
```

Notice that the window title changes to "npm".

![](http://ss.dan.cx/2016/04/cmd_28-10.13.47.png)

**Comment by vladimir-kotikov** [comment]
@Daniel15, this is neither Clink nor Cmder issue - i guess this is something related to completions for 'npm' command which is separate package

**Comment by Daniel15** [comment]
Thanks, using the latest clink-completions resolves the issue.

**Comment by gitgrimbo** [comment]
@vladimir-kotikov, @Daniel15 - Did you guys get to the bottom of this? I am using an unrelated npm script and the cmd.exe title is constantly being changed to "npm". I haven't been able to find out why this is happening.

**Comment by Daniel15** [comment]
@gitgrimbo  Upgrading clink-completions to the latest version fixed it for me, as per my last comment in this thread.
