### ISSUE TITLE
Insure CLink is only injected into CMD.EXE

### ISSUE THREAD

**Issue by DMcCunney** [mridgers/clink#400]
I have CLink here, and it works under Win10.  The problem is, CMD.EXE isn't the only shell I use.  In addition to CMD, I have JPSoftware's freeware TCC-LE, a less powerful console version of their GUI TCC app, and Win32 ports of Gnu bash, tcsh, and zsh.  I run them in ConEmu, an open source tabbed console manager.  ConEmu defaults to using tcc-le if it's present.

CLink attempts to inject itself into tcc-le, and tcc-le does horribly when it does.  Is there a convenient way to specify in autoruns that Clink only attempts to inject itself into CMD.EXE?

**>Dennis**

**Comment by mridgers** [comment]
Clink already checks its parent process to make sure it's a supported one (`cmd.exe` or `powershell.exe`). I've tried TCC-LE in ConEmu, with both Clink's autorun and installed and by manually running `clink inject`. Neither resulted in Clink running in the TCC-LE process so I can't reproduce you're issue.

**Comment by DMcCunney** [comment]
I just re-installed Clink 0.41, and tried running ConEmu.  I got

TCC LE  14.00.9 x64   Windows 10 [Version 6.3.10586]
Copyright 2016 JP Software Inc.  All Rights Reserved



Current directory:
C:\Users\Dennis

Command to be executed:
"C:\Program Files\JPSoft\TCCLE14x64\tcc.exe"


ConEmuC: Root process was alive less than 10 sec, ExitCode=2.
Press Enter or Esc to close console...

Which was TCC-LE dying horribly when Clink tried to inject itself.

The same thing happened when I uninstalled Clink 0.41 and tried again with Clink 0.47.

I'd love to know why it bites here but doesn't bite on your system.

Uninstalled again...
_______
Dennis

**Comment by mridgers** [comment]
0.4.1 is an old version which doesn't include f74f00f39ed1. I recommend you upgrade to the latest version of Clink.

**Comment by DMcCunney** [comment]
I stated in the prior reply that I *also* tried Clink 0.4.7 with the *same* results.  The current version on the Clink website is 0.4.7.  Is there something more recent?  (And could the fact I'm running the 64 bit version of TCC-LE be an issue?)

**>Dennis**

**Comment by alexandrul** [comment]
https://github.com/mridgers/clink/releases/tag/0.4.8

**Comment by mridgers** [comment]
> I stated in the prior reply that I also tried Clink 0.4.7

Yes, sorry. I missed that.

> could the fact I'm running the 64 bit version of TCC-LE be an issue?

I also used the 64-bit version, so no.

**Comment by DMcCunney** [comment]
And I just uninstalled Clink 0.4.7 and installed 0.4.8 that alexadrul supplied a link to.  I still see the same problem.  Clink behaves correctly in a CMD instance in a console.  TCC-LE dies horribly on invocation when Clink is installed.  That happens if I try to run it *outside* ConEMU, too. TCC-LE seems to be violently allergic to Clink's presence.  I'll poke around some more.  Right now, I have *no* idea what's going on.

**>Dennis**

**Comment by DMcCunney** [comment]
And a little more poking.  I uninstalled Clink 0.48, then re-installed without the Autorun option.

I can run TCC-LE under ConEMU or in its own console and it works fine.  I can run ConEMU with TCC-LE in the first tab (the default behavior, and then open a new tab with CMD.EXE and install Clink within the CMD instance from the clink.bat file.

Things go to hell in a bucket if autorun is turned on.

**>Dennis**
