### ISSUE TITLE
Build succeeds but clink doesn't work.

### ISSUE THREAD

**Issue by Avinm** [mridgers/clink#401]
I cloned the source today and built it using premake and vs2013. I targeted both x86 and x64 and copied all the files from the release dir and overwrote the ones in the clink installation dir. Clink has now stopped working without any errors. Am I missing something?

**Comment by mindw** [comment]
it seems premake5 change the default VS project characterset to UNICODE.
```lua
    characterset("MBCS")
```
should fix this. Testing.

**Comment by Avinm** [comment]
This also caused the new clink to make a lot of folders with strange characters like "振楬歮ᘀ"

**Comment by mindw** [comment]
Yes - that's what I needed to connect the dots.

**Comment by mridgers** [comment]
Wow, that's a subtle change from Premake5. That's what you get with alpha builds I suppose. Thanks for the fix @mindw.
