### ISSUE TITLE
Circumflex  & doble quote problem

### ISSUE THREAD

**Issue by xamgore** [mridgers/clink#407]
Hi there!

I'm working with git and have found some problems trying to reset commit:

```
git reset HEAD^
```

This doesn't work very well, prompt asks smth like "Continue?"

What can you advise to do in such situation? Is this behaviour ok?

**Comment by snmishra** [comment]
This is not a clink issue. ^ is the continuation character for cmd . You'll need to use ^^ to actually output a ^.

**Comment by xamgore** [comment]
@snmishra wow, thanks! What about a situation, when you want to enter multi line comment for commit?

```
git commit -m "pam pam

pam"        # try to write this
```

but actually get just `git commit -m "pam pam"`

**Comment by snmishra** [comment]
@xamgore This is probably not the forum to discuss cmd syntax. Perhaps StackOverflow? In any case, you probably want:
```bat
git commit -m "pam pam"^
" pam" 
```

**Comment by mridgers** [comment]
Yup, `^` has a special meaning to `cmd.exe` - it is used to escape characters (much like `\` in everywhere else!). Thanks @snmishra!
