### ISSUE TITLE
Error on latest pull

### ISSUE THREAD

**Issue by andalou** [mridgers/clink#408]
I'm building clink on Windows 7 Home Premium.
After updating to the latest pull, and doing 'premake5 -cc=gcc --os=windows gmake' I'm getting:

Error: premake5.lua:115: attempt to call global 'characterset' (a nil value)

Many thanks in advance,

-- 
Cesar

**Comment by mridgers** [comment]
You need to use 5.0-alpha8 or better. Premake changed the default character set to Unicode which Clink doesn't support.
