### ISSUE TITLE
Pin to task bar in windows 10

### ISSUE THREAD

**Issue by elieobeid7** [mridgers/clink#411]
If I pin Clink to task bar in windows 10, the next time I try to open it, the default command prompt will be opened instead.

**Comment by savioret** [comment]
Once you've made the pinned shortcut, right click over the cmd >> properties and change the "_Target_" to the bat destination
` c:\installpath\clink_0.X.X\clink.bat`

**Comment by elieobeid7** [comment]
what was the question again? 2016? wow thank you for answering man.
