### ISSUE TITLE
clink 0.4.8 hangs when I want to install the autorun function

### ISSUE THREAD

**Issue by jdhao** [mridgers/clink#416]
my OS is Windows 8.1 Enterprise edition (32 bit version) and previously I have been using clink 0.4.7 and everything is fine.  But when I downloaded the latest version and tried to run the command `clink_x86.exe autorun install` to install the autorun function , the cmd window just hanged forever and give no response any more. 
How can I solve this problem?

**Comment by Radiergummi** [comment]
Same problem for me, with all versions I install now though

**Comment by jdhao** [comment]
@Radiergummi , I have choose to use [cmder](https://github.com/cmderdev/cmder) and I think it is more powerful. You can switch to it.
