### ISSUE TITLE
Disable clink's M-h (Alt-h) keyboard shortcut

### ISSUE THREAD

**Issue by yogan** [mridgers/clink#426]
I have a custom key binding for <kbd>M-h</kbd> (= <kbd>Alt</kbd> + <kbd>h</kbd>) in my .inputrc. However, clink still displays its help screen when pressing this shortcut. Can I disable this somehow?

**Comment by garoto** [comment]
It's defined in `clink_inputrc_base`. Just comment all entries there.

**Comment by yogan** [comment]
Thanks, this works perfectly.
Just for reference: `clink_inputrc_base` is in the directory where clink is installed to, so probably `C:\Program Files (x86)\clink\<VERSION>\`.
