### ISSUE TITLE
Suppress Clink output on command prompt load

### ISSUE THREAD

**Issue by u01jmg3** [mridgers/clink#430]
Just wondered if there was a way to suppress the output that Clink adds when loading a command prompt?

```
Clink v0.4.7 [git:dfc95a] Copyright (c) 2012-2016 Martin Ridgers
http://mridgers.github.io/clink
```

**Comment by garoto** [comment]
clink inject --help

`
Clink v0.4.8 [git:d565ad] Copyright (c) 2012-2016 Martin Ridgers
http://mridgers.github.io/clink

  -s, --scripts <path>  Alternative path to load .lua scripts from.
  -p, --profile <path>  Specifies and alternative path for profile data.
  -q, --quiet           Suppress copyright output.
  -n, --nohostcheck     Do not check that host is a supported shell.
  -d, --pid <pid>       Inject into the process specified by <pid>.
  -a, --ansi            Target shell uses Windows' ANSI console API.
  -l, --nolog           Disable file logging.
  -h, --help            Shows this help text.
`
And then for the installing an autorun entrie:
`clink autorun install -q`

Alternatively, a simple `>nul` output redirect in either the registry Autorun entrie or via CLI will supress the initial output as well.

**Comment by u01jmg3** [comment]
Super

**Comment by u01jmg3** [comment]
I am finding that if I use the `--quiet` flag, my history stops working. Is this intended?

**Comment by garoto** [comment]
Just did a quick test and my history file seems to be updated just fine.

And just in case, my cmd autorun entrie reads: `C:\Apps\Diversos\Clink\clink_x64.exe inject -q`

I edited it to point directly to the .exe because reasons, but I don't think that make a difference.

Are you sure you haven't reached the configured history line limit?

**Comment by u01jmg3** [comment]
- History line limit has not been reached.
- Here is a demo of what I'm experiencing:

![demo](https://cloud.githubusercontent.com/assets/1266205/22161729/96cbcb9e-df43-11e6-9056-0420263cf821.gif)

**Comment by uahim** [comment]
this happens here too on a fresh install of clink 0.4.8 x64
