### ISSUE TITLE
Stopped working in Insider build 15002

### ISSUE THREAD

**Issue by chris-morgan** [mridgers/clink#431]
I’m in the Windows Insider Program, and in build 15002 which was just released to the Fast ring (Build 15002.rs_prerelease.170102-1700) Clink has stopped working.

`clink inject` just doesn’t do anything. No apparent errors or anything.

**Comment by garoto** [comment]
Any clink.log in `%localappdata%\clink`?

**Comment by chris-morgan** [comment]
```
 9120 do_inject                  185 System: ver=6.2 0.0 arch=9 cpus=4 cpu_type=8664 page_size=4096
 9120 do_inject                  190 Version: 0.4.8
 9120 do_inject                  191 DLL: C:\Program Files (x86)\clink\0.4.8\clink_dll_x64.dll
 9120 do_inject                  193 Parent pid: 3620
 9120 check_dll_version           52 DLL version: 00000004 000881c4
 9120 do_inject_impl             283 Creating remote thread at 00007FF811FEFFF0 with parameter 000001361A8A0000
 3620 set_rl_readline_name        58 Setting rl_readline_name to 'cmd.exe'
 3620 hook_trap_veh              120 VEH hit - caller is 00007FF7AAFBD475.
 3620 hook_jmp                   408 Attemping jump hook.
 3620 hook_jmp                   409 Target is kernelbase.dll, ReadConsoleW @ 00007FF811BCB6D0
 3620 hook_jmp_impl              351 Attempting to hook at 00007FF811BCB6D0 with 00007FFFF83F63A4
 3620 hook_jmp_impl              360 Unable to match instruction 24048B48
 3620 hook_jmp                   415 Jump hook failed.
 3620 apply_hook_jmp              73 Unable to hook ReadConsoleW in kernelbase.dll
 3620 hook_trap_veh              125 Hook trap 00007FFFF83F62D8 failed.
```

**Comment by fluffynuts** [comment]
Same here; however, it must be noted that 15002 introduced a lot of buggy behavior for me too (default audio device not being used for playback through waveout and a couple of "older" applications (like SysInternals' AutoRuns) not displaying correctly). So as much as I'd like this fixed, it may just be unfuxed at the next update.

**Comment by karli2000** [comment]
Still not working in 15007 :( I really, really miss it!
Logfile is the same:

>  8544 do_inject                  185 System: ver=6.2 0.0 arch=9 cpus=4 cpu_type=8664 page_size=4096
 8544 do_inject                  190 Version: 0.4.8
 8544 do_inject                  191 DLL: C:\Program Files (x86)\clink\0.4.8\clink_dll_x64.dll
 8544 do_inject                  193 Parent pid: 12308
 8544 check_dll_version           52 DLL version: 00000004 000881c4
 8544 do_inject_impl             283 Creating remote thread at 00007FFE6FE000E0 with parameter 000001C248CB0000
12308 set_rl_readline_name        58 Setting rl_readline_name to 'cmd.exe'
12308 hook_trap_veh              120 VEH hit - caller is 00007FF7DABED475.
12308 hook_jmp                   408 Attemping jump hook.
12308 hook_jmp                   409 Target is kernelbase.dll, ReadConsoleW @ 00007FFE6D25B6D0
12308 hook_jmp_impl              351 Attempting to hook at 00007FFE6D25B6D0 with 00007FFE5EFC63A4
12308 hook_jmp_impl              360 Unable to match instruction 24048B48
12308 hook_jmp                   415 Jump hook failed.
12308 apply_hook_jmp              73 Unable to hook ReadConsoleW in kernelbase.dll
12308 hook_trap_veh              125 Hook trap 00007FFE5EFC62D8 failed.

**Comment by jdmansour** [comment]
Same for build 15014:
```
12308 do_inject                  185 System: ver=6.2 0.0 arch=9 cpus=4 cpu_type=8664 page_size=4096
12308 do_inject                  190 Version: 0.4.8
12308 do_inject                  191 DLL: C:\Program Files (x86)\clink\0.4.8\clink_dll_x64.dll
12308 do_inject                  193 Parent pid: 15696
12308 check_dll_version           52 DLL version: 00000004 000881c4
12308 do_inject_impl             283 Creating remote thread at 00007FFACCEE00E0 with parameter 000001DED00B0000
15696 set_rl_readline_name        58 Setting rl_readline_name to 'cmd.exe'
15696 hook_trap_veh              120 VEH hit - caller is 00007FF77796D475.
15696 hook_jmp                   408 Attemping jump hook.
15696 hook_jmp                   409 Target is kernelbase.dll, ReadConsoleW @ 00007FFACBC6B6D0
15696 hook_jmp_impl              351 Attempting to hook at 00007FFACBC6B6D0 with 00007FFA9D6263A4
15696 hook_jmp_impl              360 Unable to match instruction 24048B48
15696 hook_jmp                   415 Jump hook failed.
15696 apply_hook_jmp              73 Unable to hook ReadConsoleW in kernelbase.dll
15696 hook_trap_veh              125 Hook trap 00007FFA9D6262D8 failed.
```

**Comment by chris-morgan** [comment]
Interesting fact I just discovered by accident: although clink is broken in C:\WINDOWS\system32\cmd.exe, it works in C:\Windows\SysWOW64\cmd.exe.

I have no idea what the practical difference between the two is, if any.

**Comment by jdmansour** [comment]
That makes sense, C:\Windows\SysWOW64\cmd.exe is the 32 bit version. It seems only the 64 bit version changed in an incompatible way.

**Comment by chris-morgan** [comment]
At 15031 it’s back to working again.

**Comment by KayLeung** [comment]
partial working it seems at 15042. aliases (doskey) still not working.

**Comment by chris-morgan** [comment]
True, I had noticed that a doskey macro wasn’t working but hadn’t investigated it. `doskey /macros` shows the macros, but they’re not functioning.

**Comment by chris-morgan** [comment]
Closing in favour of #438 which deals with the specific new problem.
