### ISSUE TITLE
History stops working when --quiet flag is used

### ISSUE THREAD

**Issue by u01jmg3** [mridgers/clink#432]
- I am finding that if I use the `--quiet` flag, my history stops working
- To confirm, history line limit has not been reached and my issue relates to no history being available when I arrow down (rather than the history not being updated).
- Tried `"C:\Program Files (x86)\clink\0.4.8\clink_x64.exe" inject --quiet` but still no history
- Here is a demo of what I'm experiencing:

![demo](https://cloud.githubusercontent.com/assets/1266205/22161729/96cbcb9e-df43-11e6-9056-0420263cf821.gif)

**Comment by chrisant996** [comment]
Thank you for the video!  You probably figured it out a long time ago, but the video shows that `--quiet` is preceded by `--profile`.  The `--profile` option takes a mandatory argument indicating the profile directory.  So the sequence `--profile --quiet ~\clink` causes "--quiet" to be used as the profile directory.  This is behaving correctly, given the input.

**Comment by u01jmg3** [comment]
Exactly as @chrisant996 has stated.

❌

```
"C:\Program Files (x86)\clink\0.4.9\clink.bat" inject --autorun --profile --quiet ~\clink
```

✔️

```
"C:\Program Files (x86)\clink\0.4.9\clink.bat" inject --autorun --quiet --profile ~\clink
```
