### ISSUE TITLE
Change location of log file

### ISSUE THREAD

**Issue by thdoan** [mridgers/clink#440]
I noticed that clink creates a log file  in `C:\Users\username\AppData\Local\clink`. If I want to make it portable, how can I specify the location of the log file in clink.bat, or tell it to generate the log file in the same directory as the executable?

**Comment by eadmaster** [comment]
i second the request, already asked [here](https://github.com/mridgers/clink/issues/187) and [here](https://github.com/mridgers/clink/issues/154).

**Comment by PNBRQK** [comment]
The log directory is hard-coded in the program. Changing it requires a small tweak on clink/shared/paths.c (as below) , then a rebuild.

`void get_log_dir(char* buffer, int size)
{
	get_dll_dir(buffer, size);
}`
