### ISSUE TITLE
ConEmu and clink Hangs

### ISSUE THREAD

**Issue by OldMcWeb** [mridgers/clink#445]
With ConEmu 170402 x64 and clink 0.4.8 some kind of hang appears 
when minimize the window to tray.
No input is possible.

I can reproduce it after a few trys:

1. Type in a command like dir and hit enter
2. Minimize
3. Maximize 
4. Browse History
5. goto 1.

After some trys the cursor is heavily blinking(like pressing arrow down permanently) and no input is possible.
Maybe its an conemu problem?

**Comment by cronhan** [comment]
I'm also seeing this, but I could never figure out how to reproduce the issue.

**Comment by OldMcWeb** [comment]
I found an alternate way to reproduce it:
Open ConEmu with clink

1. doubleclick somewhere in the window 
2. Then single click in the window again and it freezes for a while.

**Comment by easybe** [comment]
Still a problem with latest stable ConEmu. I am not a Windows hacker, so rather hard for me to debug :(

![prompt](https://user-images.githubusercontent.com/594536/29658345-cc287028-88ba-11e7-8a64-842e69b0280b.gif)

**Comment by Mike737377** [comment]
Issue also occurs with Clink v0.4.7

**Comment by rgd** [comment]
I've seen this in various similar scenarios but it *does* seem to eventually "get better" - like after 1+ minutes.

**Comment by Discipe** [comment]
I could constantly reproduce the issue on Conemu with Clink 0.4.7 on Win7.
I've updated Conemu to latest stable version (16xxxx) and Clink to 0.4.9 - issue is gone now.

**Comment by wuy3** [comment]
This is still happening to me with Cmder 1.3.5 (ConEmu 180206). Its really impacting my productivity, if anyone can tell me how to update or disable clink in Cmder please let me know. Thanks :)

**Comment by OldMcWeb** [comment]
All issues solved with updating ConEmu (in my case 190623 Alpha)
