### ISSUE TITLE
Clink seems to cause latest Fall Creator Update of Win 10 to BSOD

### ISSUE THREAD

**Issue by attzonko** [mridgers/clink#472]
At a random time I saw dialog pop up saying "clink_x64 has stopped working"

Immediately after the PC got BSOD. This was the second crash since the Windows update, I was lucky enough to see the dialog prior to the BSOD. The minidump I got was not much help.

**Comment by chrisant996** [comment]
The mridgers repo is abandoned.  Use https://github.com/chrisant996/clink, which is alive and well.
