### ISSUE TITLE
clink 0.4.9 on Win XP & XP x64: Not a valid Win32 application

### ISSUE THREAD

**Issue by GrandAdmiralThrawn** [mridgers/clink#485]
Once again (like [[here](https://github.com/mridgers/clink/issues/278)]), clink 0.4.9 no longer works on XP, as it's built for NT 6.0 - Windows Vista. Since even the latest Visual Studio 2017 still has a platform toolset for targeting XP (v141_xp), this should be easily fixable.

Out of curiosity, I modified the binary headers of clink_x64.exe and clink_dll_x64.dll on my XP x64 machine with CFF Explorer to fix this issue (setting MajorSubsystemVersion to 0005 and MinorSubsystemVersion to 0002). After the modification, clink still works fine on XP.

Thus, I would like to request the next versions to be built with an XP compatible platform toolset again, as API-wise, compatibility with XP has not been broken (yet). So this shouldn't be too much work, just a few clicks.

**Comment by GrandAdmiralThrawn** [comment]
I would like to kindly ask you not to make comments like that, especially when not knowing anything about the systems this is about. I believe comments like that do not contribute anything constructive.

Thank you very much.

**Comment by ruthan** [comment]
Retro is good, i also have this problem..

**Comment by GrandAdmiralThrawn** [comment]
Almost 2 years later, it appears that there is no interest in having the platform toolset reconfigured to allow for XP / XP x64 and Server 2003 / Server 2003 x64 support.

I thus consider the binary hack via CFF Explorer or modbin the correct approach for regular users and a re-compilation of clink with the v120_xp, v140_xp or v141_xp MSVC platform toolsets for advanced users.

On a side note: I tried to compile this with the v90 toolset for Windows 2000, but failed. Too bad, but well...

**Comment by Stanzilla** [comment]
Almost two years later there is even less of a reason to use Windows XP as well.

**Comment by GrandAdmiralThrawn** [comment]
> 
> 
> Almost two years later there is even less of a reason to use Windows XP as well.

That's a personal opinion, not a fact and it's not providing any helpful technical input about backporting the software to any operating system.

So, since you expressed your opinion, here's my own in reply to yours: There is always a reason for whatever people do. I'm personally running machines with MS-DOS, Windows 3.11, Windows NT 3.51 SP5, Windows NT 4.0 SP6a, Windows 95C, Windows 98 SE, Windows 2000 Pro & Server, XP 32-bit SP3, XP x64 SP2, Server 2003 x64 SP2, Vista SP2, and 7 SP1 and IBM OS/2 Warp4, those are the ones no longer officially supported for consumers. Aside from that there are many others (Solaris, Linux, BSD Unices, Win10, macOS, etc.). It's mostly for learning and experimentation regarding software portability, usually C and C++ code, sometimes including binary program hacks (like injection of stub DLLs, change of load-time library imports in PE32 headers, etc.).

Just because you may not see any reason for running some those systems doesn't mean others can't. ;)

I would - of course - welcome any input detailing how to backport this software to v90 or v70 platform toolsets on Microsoft operating systems. With that I could release my own builds for older systems.

After all, clink is a pretty useful tool!

**Comment by sskras** [comment]
> Almost two years later there is even less of a reason to use Windows XP as well.

It could be useful for [ReactOS](https://github.com/reactos/reactos), which is targeting WS2003 currently.

**Comment by GrandAdmiralThrawn** [comment]
> 
> 
> > Almost two years later there is even less of a reason to use Windows XP as well.
> 
> It could be useful for [ReactOS](https://github.com/reactos/reactos), which is targeting WS2003 currently.

Maybe, yes. If currect ReactOS reports 5.2 as the kernel version, then my simple PE header fix would work for it as well. Haven't played around with ReactOS in years though.

It's really simple to apply. Or maybe I should just share my own XP builds somewhere (I need to re-attempt a compilation first)? Or just the modified binary programs?
