### ISSUE TITLE
Clink handles CTRL+C incorrectly

### ISSUE THREAD

**Issue by classix-do** [mridgers/clink#486]
I noticed a strange inconsistency when pressing **CTRL+C** during a `SET /P`. Sometimes CLINK doesn't prompt the user and simply skips to the next line, sometimes it results in a SyntaxError and somtimes it works just as expected. This problem doesn't occur when running the batch file with the original cmd.

I am running clink on a Win 10 Pro 64-Bit machine.

**test.bat**

    @echo off
    REM we don't want to influence the next calls
    SETLOCAL enabledelayedexpansion
    
    REM the problem only occurs reliably with an if statement
    IF "" == "" (
      SET /P choice=What do you like? 
    )
    
    REM this gets printed even though CTRL+C is pressed
    ECHO So you like !choice!...
    ENDLOCAL

**sample session**

    Clink v0.4.9 [git:2fd2c2] Copyright (c) 2012-2016 Martin Ridgers
    http://mridgers.github.io/clink
    
    C:\Users\do\Desktop>test
    What do you like? burger
    So you like burger...
    
    C:\Users\do\Desktop>test
    What do you like? ^CSyntaxfehler.
    
    C:\Users\do\Desktop>test
    What do you like? ^CBatchvorgang abbrechen (J/N)? J
    
    C:\Users\do\Desktop>test
    What do you like? ^CSyntaxfehler.
    C:\Users\do\Desktop>test
    What do you like? So you like ...
    
    C:\Users\do\Desktop>test
    What do you like? ^CBatchvorgang abbrechen (J/N)? J
    
    C:\Users\do\Desktop>test
    What do you like? ^CBatchvorgang abbrechen (J/N)? J
    
    C:\Users\do\Desktop>test
    What do you like? ^CBatchvorgang abbrechen (J/N)? J
    C:\Users\do\Desktop>test
    What do you like? ^CSyntaxfehler.
    C:\Users\do\Desktop>test
    What do you like? ^CSo you like ...
    
    C:\Users\do\Desktop>test
    What do you like? ^CBatchvorgang abbrechen (J/N)? J
    
    C:\Users\do\Desktop>test
    What do you like? ^CBatchvorgang abbrechen (J/N)? J
    
    C:\Users\do\Desktop>test
    What do you like? ^CSo you like ...
    
    C:\Users\do\Desktop>

**Comment by chrisant996** [comment]
Sounds related to #398.

**Comment by chrisant996** [comment]
This works as expected in [chrisant996/clink](https://github.com/chrisant996/clink).

_**However,**_ when the `cmd.get_errorlevel` Clink setting is enabled, then the behavior still goes wrong in the way reported here.

**Comment by chrisant996** [comment]
I confirmed this issue **can** occur in cmd.exe by itself, independently from Clink:

![image](https://user-images.githubusercontent.com/17440311/127065134-556ea94e-6b25-4ce4-a812-1532f7bd86b1.png)

This issue is unrelated to Clink.
