### ISSUE TITLE
Is it possible to switch clink profiles after injection

### ISSUE THREAD

**Issue by samiksome** [mridgers/clink#496]
I tried using `clink.exe inject --profile <profile_dir>` after injecting it once but it doesn't seem to work.

**Comment by chrisant996** [comment]
Yes, the fork at [chrisant996/clink](https://github.com/chrisant996/clink) can.  You can use `set CLINK_PROFILE=profile_dir` to change the profile directory in the current instance.

**Comment by samiksome** [comment]
@chrisant996  Thank you. I have been using your fork for a while.
