### ISSUE TITLE
clink turns off branch name and color syntax on Cmder

### ISSUE THREAD

**Issue by folmert** [mridgers/clink#513]
Before installing clink:
![clink1](https://user-images.githubusercontent.com/4053141/53238904-dea92000-369a-11e9-92b9-be8cffc7449e.jpg)

After installing clink:
![clink2](https://user-images.githubusercontent.com/4053141/53238910-e36dd400-369a-11e9-882f-e8e8cf1165b6.jpg)

System: Windows 10
cmd: ConEmu 161206 [64], Cmder fork

**Comment by DRSDavidSoft** [comment]
Cmder is already running Clink, are you installing a seperate Clink in it?

If you are running an external Clink in Cmder, it'll probably start with its own customization file, which lacks [clink-completions](https://github.com/vladimir-kotikov/clink-completions) (which provides the branch name) and Cmder's customized shell.

In any case, you should not launch another Clink in Cmder, you should instead edit the already included Clink in Cmder.

**Comment by Stanzilla** [comment]
Yeah don't install clink manually

**Comment by folmert** [comment]
> Cmder is already running Clink

Thanks, I didn't know that. I assumed it didn't include Clink because the history command didn't work on Cmder. But it's possible to run the history command [with this script](https://superuser.com/a/1212063/274832).
