### ISSUE TITLE
Doskey $T not handled properly

### ISSUE THREAD

**Issue by hulucc** [mridgers/clink#516]
The `echo on` in `doskey test=echo off $T echo 3 $T echo on` won't be executed under clink.
But works fine in plain cmd.
Tested with lastest version: `1.0.0a1.823d84` on Windows 10 1809

**Comment by chrisant996** [comment]
This is fixed by [cdb8558](https://github.com/chrisant996/clink/commit/cdb8558483cc51522ab7cc34d28c397756e35a33) in the chrisant996 fork.
