### ISSUE TITLE
history search by typing few first symbols and pressing up/down arrows 

### ISSUE THREAD

**Issue by dkhokhlov** [mridgers/clink#525]
Is it possible to do history search by typing few first symbols and pressing up/down arrows?

Like in bash using this config:
bind '"\e[A"':history-search-backward
bind '"\e[B"':history-search-forward

**Comment by garoto** [comment]
```
"\e`H": history-search-backward # up arrow
"\e`P": history-search-forward  # down arrow
```

**Comment by dkhokhlov** [comment]
Simple search works, but it does not filter. 
Here is how it works in bash:
1. type first symbol of command you are searching
2. press UP arrow
Expected:
- prompt shows first command from the history that is starting with the typed symbol in 1
3. press UP arrow again
Expected:
- prompt shows second command from the history that starts with the typed symbol in 1

Possible?

**Comment by dkhokhlov** [comment]
Solution:
add the following lines to readline config file: ..../clink/profile/clink_inputrc

"\e`H": history-search-backward # up arrow
"\e`P": history-search-forward  # down arrow
