### ISSUE TITLE
add pwd alias

### ISSUE THREAD

**Issue by zodman** [mridgers/clink#527]
![](https://i.imgur.com/9CS31DA.png)

**Comment by garoto** [comment]
`doskey pwd=echo %cd%`

**Comment by chrisant996** [comment]
I think the screen shot is trying to ask "why are these [?] characters displaying instead of the fancy triangle symbols?"

The selected font doesn't have the fancy triangle symbols.  Pick a font that has them, such as Fira Code.

**Comment by zodman** [comment]
> I think the screen shot is trying to ask "why are these [?] characters displaying instead of the fancy triangle symbols?"
> 
> The selected font doesn't have the fancy triangle symbols. Pick a font that has them, such as Fira Code.

No, the symbols not related. Only add alias of pwd ....

**Comment by chrisant996** [comment]
Is it a request to automatically add pwd by default, without any user configuration needed?  I think it's useful (and considerate) if clink doesn't have too many built in aliases.

Would another way to address the issue be to have a special aliases file that gets loaded automatically?  And maybe some sample aliases files that have collections of things like a pwd alias?  That way one could just copy an alias file into place and not need any other configuration.  Similar to how the inputrc file works.

**Comment by garoto** [comment]
Welp, I guess the Windows native way to load a file with doskey macros at `cmd.exe` startup is to setup an `AutoRun` entry in `HKEY_CURRENT_USER\Software\Microsoft\Command Processor` (just like `clink autorun` does) and have it load a macros definition file, like in the screenshot below:

https://0x0.st/il0I.png

Not sure if worthwhile to spend time and effort implementing this functionality when its already there.
