### ISSUE TITLE
Is this project still alive? Clink v1.0.0.a1 doesn't support cyrillic characters keyboard input on Windows 10 with console V2

### ISSUE THREAD

**Issue by Slach** [mridgers/clink#544]
@mridgers  please look short screencast
https://recordit.co/nL43B3TOJm
chcp 1251
chcp 65001
russian input doesn't work

also doesn't work
```
[HKEY_CURRENT_USER\Console]
"ForceV2"=dword:00000001
```
and
```
[HKEY_CURRENT_USER\Console]
"ForceV2"=dword:00000000
```

**Comment by chrisant996** [comment]
I can reproduce this.  I'll look into fixing it in the [chrisant996/clink](https://github.com/chrisant996/clink) fork.  And thank you for the screencast - very helpful!

**Comment by Slach** [comment]
@chrisant996 wow, great thanks a lot for your efforts!

**Comment by Slach** [comment]
@chrisant996 thanks a lot for your efforts, all works fine now
