### ISSUE TITLE
Keyboard Shortcuts not working on Windows 11

### ISSUE THREAD

**Issue by YanlongLi** [mridgers/clink#561]
Just realized that all clink keyboard shortcuts are not working anymore after I upgraded to Windows 11. Anyone knows the causes or how to get around?

**Comment by chrisant996** [comment]
This repo has been abandoned for years.  https://github.com/chrisant996/clink is a highly active fork with official releases.  Please try using the latest Clink from there, and open an issue in that repo if there are problems with Windows 11.

**Comment by YanlongLi** [comment]
@chrisant996 You really saved my day, just tried the latest release from https://github.com/chrisant996/clink and it works for me. Thanks!
