### ISSUE TITLE
clink under Windows 11 does not seem to properly hook readline

### ISSUE THREAD

**Issue by ben-may** [mridgers/clink#566]
When using clink on windows 11 we find that it does not seem to properly hook things, and I also don't see the lua scripts being run either.  Not sure what is going on TBH.  Are you able to run clink properly on Windows 11?  I am using v0.4.9.

**Comment by Ircama** [comment]
This repo might no longer be maintained.
Please switch to https://github.com/chrisant996/clink

**Comment by ben-may** [comment]
I posted my question over at the other repo listed above:
https://github.com/chrisant996/clink/issues/174
