### ISSUE TITLE
Arrow Key Command History Navigation Not Working Using Windows 10's Built-in 'Touch Keyboard'

### ISSUE THREAD

**Issue by richaardvark** [mridgers/clink#571]
Hello,

My main, everyday Windows machine is a tablet PC with a touchscreen and does not have a built-in keyboard. This tablet PC is connected to an LCD television and is typically operated from my couch. While there is a physical, wireless USB keyboard (and also a mouse) connected to my computer, it is frequently misplaced (also, I'm lazy) and thus I find myself most frequently using the built-in "Touch Keyboard" from the Windows 10 taskbar, operating it from the wireless mouse. 

With a command prompt open, nothing happens when I click the Up and Down arrow keys on the on-screen Touch Keyboard - no command history is displayed.  However, it is properly shown if I press the up and down arrow keys on the physical, USB-connected keyboard.  Why does the virtual keyboard not work?  Many people use convertible/"2-in-1" tablet PCs these days especially when traveling or when working out in the field and may not always have a physical keyboard available and are dependent on the on-screen virtual touch keyboard. 

I am running Clink v0.4.9 [git:2fd2c2] on Windows 10 version 10.0.19044.1503.

**Comment by chrisant996** [comment]
You're using a very old version.  This repo was abandoned several years ago.

As noted in many other issues logged here, the fork at http://github.com/chrisant996/clink is alive and well.  You should consider upgrading to that.  The issue you reported here works fine there.

**Comment by richaardvark** [comment]
> You're using a very old version. This repo was abandoned several years ago.
> 
> As noted in many other issues logged here, the fork at [http://github.com/chrisant996/clink](https://github.com/chrisant996/clink) is alive and well. You should consider upgrading to that. The issue you reported here works fine there.

Thanks!  I had downloaded the version that comes up first in Google, [from what at least appears to be the application's homepage/developer site](https://mridgers.github.io/clink/). I realize now this is outdated.   Is there any way to update/remove this website or change its position in a Google search?  You are probably already aware of all of this but I have to imagine a good portion of users (if not a majority) are downloading this super old version and aren't even aware of it (like myself).

I now have v1.3.4 installed ✔
Unfortunately my issue still persists (not being able to navigate using the Windows 10 Touch Keyboard. I'll open an issue on the active/current repo.
