### ISSUE TITLE
Copy paste repeats 2nd char

### ISSUE THREAD

**Issue by krish-gh** [mridgers/clink#575]
It's a weird issue. When pasting a copied command/text to terminal, it repeats the 2nd char. I tried powershell and cmd without clink where it behaves normally. Also, tried with vanilla clink without any cool prompt. So seems like some issue in clink in particular.

For example, here below I am pasting some random stuffs from notepad to demonstrate:
![image](https://user-images.githubusercontent.com/2088089/192421138-0d47c90a-8702-437c-bd20-d9f10dfefef9.png)

**Comment by chrisant996** [comment]
Thanks for reporting it.

This is the old repo.

The current repo is https://github.com/chrisant996/clink.

The issue was reported earlier today as https://github.com/chrisant996/clink/issues/348, and the fix was published as v1.3.44.
