### ISSUE TITLE
Cycle Auto-Complete Options

### ISSUE THREAD

**Issue by grantelledge** [mridgers/clink#583]
Hello! I can't find a solution to cycle through auto-complete options for more recent versions (I'm on 1.6.0). See [here](https://github.com/mridgers/clink/issues/190) for a parallel solution on 0.4. Thanks in advance!

**Comment by chrisant996** [comment]
You're still in the abandoned mridgers repo.

Use the chrisant996 repo.

Also, the documentation covers your question, and it's a setting, and it's mentioned in the Getting Started section.

**Comment by chrisant996** [comment]
@grantelledge Can you please close this issue?  It's in the wrong repo, and Martin is gone so the person who can close an issue in this repo is the person who opened it.
