### ISSUE TITLE
Is it possible for clink to work in powershell?

### ISSUE THREAD

**Issue by ghost** [mridgers/clink#74]
_From [dont...@gmail.com](https://code.google.com/u/105622296508727703712/) on November 30, 2012 14:31:34_

I really like clink, but powershell is usually my terminal of choice on Windows. I naively tried to load clink in my powershell profile with this command:

& 'C:\Program Files (x86)\clink\0.2.1\clink_x86.exe' inject

But when that runs I'm presented with an error:
Failed to load clink.
See log for details (C:\Users\e.dontje\AppData\Local\clink).

Contents of that log file:
do_inject():175 -- System: ver=6.2 0.0 arch=0 cpus=4 cpu_type=586 page_size=4096
do_inject():180 -- Version: 0.2.1
do_inject():181 -- DLL: C:\Program Files (x86)\clink\0.2.1\clink_dll_x86.dll
do_inject():183 -- Parent pid: 5940
check_dll_version():49 -- DLL version: 00000002 0001028e
do_inject():253 -- Creating remote thread at 774CF864 with parameter 02F80000
validate_parent_process():330 -- Failed to find base address for 'cmd.exe'.

That makes sense since I'm not running in cmd.exe. Is powershell support planned?

_Original issue: http://code.google.com/p/clink/issues/detail?id=75_

**Comment by felixhao28** [comment]
Newer version of PowerShell has built-in commands to achieve this:

```powershell
# Bash-like completion
Set-PSReadlineKeyHandler -Key Tab -Function Complete
```

or

```powershell
# Bash-like completion with an interactive menu
Set-PSReadlineKeyHandler -Key Tab -Function MenuComplete
```
