### ISSUE TITLE
Support for custom aliases

### ISSUE THREAD

**Issue by ghost** [mridgers/clink#92]
_From [matri...@gmail.com](https://code.google.com/u/107149018671713641663/) on January 24, 2013 15:06:52_

Would be nice to have ability to have custom aliases that we can use with Clink and with ability to take them with us on pen-drive or sync(backup) them between computers. What version of the product are you using? On what operating system? Clink 0.2.1
Windows 7 x32 Please provide any additional information below. Could be stored in 'clink_aliases' file in user directory.

Best regards,
Dobrosław Żybort

_Original issue: http://code.google.com/p/clink/issues/detail?id=93_

**Comment by SelaO-AL** [comment]
How do you add them permanently? (I'd rather not mess with the registry like I saw somewhere else)

**Comment by garoto** [comment]
You need pass a macrofile argument to doskey.exe, like this `doskey.exe /macrofile=C:\BIN\doskeymacros.mac`, where macrofile is a simple text file that holds your macro definitions in the form of  `macroname=command <+args>`,  (e.g. "cat=type $1").

I guess the easiest way to automate this task is via cmd.exe `Autorun` registry value located at `HKEY_CURRENT_USER\Software\Microsoft\Command Processor`.

**Comment by SelaOAL** [comment]
So it will need to run something every time to register the aliases? Seems tedious and inefficient.

Maybe this feature should be added to clink so there will be a simple API like in cygwin.

**Comment by garoto** [comment]
I don't know, is it that much different from Bash executing `.bashrc ` everytime it spawns?

If manipulating registry entries are a no-no,  one could also make a cmd.exe shortcut that reads:
`C:\Windows\System32\cmd.exe /k "C:\Apps\Diversos\Clink\clink_x64.exe inject&&doskey.exe /macrofile=C:\BIN\doskeymacros.mac"`

Or even better, point it to a .bat file that does more complex initializations with error checking and whatnot. It's very flexible.

**Comment by leonardopsantos** [comment]
> You need pass a macrofile argument to doskey.exe, like this `doskey.exe /macrofile=C:\BIN\doskeymacros.mac`, where macrofile is a simple text file that holds your macro definitions in the form of `macroname=command <+args>`, (e.g. "cat=type $1").
> 
> I guess the easiest way to automate this task is via cmd.exe `Autorun` registry value located at `HKEY_CURRENT_USER\Software\Microsoft\Command Processor`.

Sorry for posting on a closed issue, but my `Autorun` key is already populated by 
`"C:\Program Files (x86)\clink\0.4.9\clink.bat" inject --autorun --profile ~\clink`.

How do I change that to call doskey with the aliases file?

Thank you!

**Comment by garoto** [comment]
`clink.bat inject --autorun` [...]

What's the point of the `--autorun` switch? Does it even exits?

**Comment by battlesteel** [comment]
> > You need pass a macrofile argument to doskey.exe, like this `doskey.exe /macrofile=C:\BIN\doskeymacros.mac`, where macrofile is a simple text file that holds your macro definitions in the form of `macroname=command <+args>`, (e.g. "cat=type $1").
> > I guess the easiest way to automate this task is via cmd.exe `Autorun` registry value located at `HKEY_CURRENT_USER\Software\Microsoft\Command Processor`.
> 
> Sorry for posting on a closed issue, but my `Autorun` key is already populated by
> `"C:\Program Files (x86)\clink\0.4.9\clink.bat" inject --autorun --profile ~\clink`.
> 
> I changed it to
> 
> "C:\Program Files (x86)\clink\0.4.9\clink.bat" inject --autorun --profile ~\clink && doskey.exe /macrofile=%LOCALAPPDATA%\clink\aliases
> 
> Works like a charm (especially if you add Cygwin`s /bin folder to your path)!

Thanks @leonardopsantos !
